/* Priyaan Hub — catalog of every Scouting America merit badge (139, as listed by the U.S. Scouting Service Project, Sept 2026).
   One badge per line so it is easy to edit. `pdf` is the file name of the free USSSP merit badge workbook:
   online at MB.workbookBase + pdf, or offline at badges/pdf/<pdf> after running `node fetch_workbooks.js`.
   USSSP terms allow local personal/Scouting use of the workbooks but not electronic redistribution — that is why the
   PDFs are downloaded to your device instead of being committed to this repository. */
var MB = window.MB = window.MB || {};   // `var` so this also loads in Node (fetch_workbooks.js)
MB.workbookBase = 'http://usscouts.org/mb/worksheets/';           // + pdf
MB.requirementsBase = 'http://usscouts.org/mb/';                   // + usssp + '.asp'  (requirements text)
MB.officialBase = 'https://www.scouting.org/merit-badges/';        // + id + '/'       (Scouting America page)
MB.localBase = 'badges/pdf/';                                       // offline copies
MB.CATALOG = [
  {"id": "american-business", "name": "American Business", "usssp": "mb015", "pdf": "American-Business.pdf"},
  {"id": "american-cultures", "name": "American Cultures", "usssp": "mb017", "pdf": "American-Cultures.pdf"},
  {"id": "american-heritage", "name": "American Heritage", "usssp": "mb016", "pdf": "American-Heritage.pdf"},
  {"id": "american-labor", "name": "American Labor", "usssp": "mb121", "pdf": "American-Labor.pdf"},
  {"id": "animal-science", "name": "Animal Science", "usssp": "mb018", "pdf": "Animal-Science.pdf"},
  {"id": "animation", "name": "Animation", "usssp": "mb158", "pdf": "Animation.pdf"},
  {"id": "archaeology", "name": "Archaeology", "usssp": "mb132", "pdf": "Archaeology.pdf"},
  {"id": "archery", "name": "Archery", "usssp": "mb019", "pdf": "Archery.pdf"},
  {"id": "architecture", "name": "Architecture", "usssp": "mb020", "pdf": "Architecture.pdf"},
  {"id": "art", "name": "Art", "usssp": "mb021", "pdf": "Art.pdf"},
  {"id": "astronomy", "name": "Astronomy", "usssp": "mb022", "pdf": "Astronomy.pdf"},
  {"id": "athletics", "name": "Athletics", "usssp": "mb023", "pdf": "Athletics.pdf"},
  {"id": "automotive-maintenance", "name": "Automotive Maintenance", "usssp": "mb127", "pdf": "Automotive-Maintenance.pdf"},
  {"id": "aviation", "name": "Aviation", "usssp": "mb025", "pdf": "Aviation.pdf"},
  {"id": "backpacking", "name": "Backpacking", "usssp": "mb026", "pdf": "Backpacking.pdf"},
  {"id": "basketry", "name": "Basketry", "usssp": "mb027", "pdf": "Basketry.pdf"},
  {"id": "bird-study", "name": "Bird Study", "usssp": "mb029", "pdf": "Bird-Study.pdf"},
  {"id": "bugling", "name": "Bugling", "usssp": "mb032", "pdf": "Bugling.pdf"},
  {"id": "camping", "name": "Camping", "usssp": "mb001", "pdf": "Camping.pdf", "eagle": "required"},
  {"id": "canoeing", "name": "Canoeing", "usssp": "mb033", "pdf": "Canoeing.pdf"},
  {"id": "chemistry", "name": "Chemistry", "usssp": "mb034", "pdf": "Chemistry.pdf"},
  {"id": "chess", "name": "Chess", "usssp": "mb147", "pdf": "Chess.pdf"},
  {"id": "citizenship-in-society", "name": "Citizenship in Society", "usssp": "mb160", "pdf": "Citizenship-in-Society.pdf", "eagle": "required", "note": "Added 2022"},
  {"id": "citizenship-in-the-community", "name": "Citizenship in the Community", "usssp": "mb002", "pdf": "Citizenship-in-the-Community.pdf", "eagle": "required"},
  {"id": "citizenship-in-the-nation", "name": "Citizenship in the Nation", "usssp": "mb003", "pdf": "Citizenship-in-the-Nation.pdf", "eagle": "required"},
  {"id": "citizenship-in-the-world", "name": "Citizenship in the World", "usssp": "mb004", "pdf": "Citizenship-in-the-World.pdf", "eagle": "required"},
  {"id": "climbing", "name": "Climbing", "usssp": "mb133", "pdf": "Climbing.pdf"},
  {"id": "coin-collecting", "name": "Coin Collecting", "usssp": "mb035", "pdf": "Coin-Collecting.pdf"},
  {"id": "collections", "name": "Collections", "usssp": "mb128", "pdf": "Collections.pdf"},
  {"id": "communication", "name": "Communication", "usssp": "mb005", "pdf": "Communication.pdf", "eagle": "required"},
  {"id": "composite-materials", "name": "Composite Materials", "usssp": "mb137", "pdf": "Composite-Materials.pdf"},
  {"id": "cooking", "name": "Cooking", "usssp": "mb038", "pdf": "Cooking.pdf", "eagle": "required"},
  {"id": "crime-prevention", "name": "Crime Prevention", "usssp": "mb131", "pdf": "Crime-Prevention.pdf"},
  {"id": "cycling", "name": "Cycling", "usssp": "mb039", "pdf": "Cycling.pdf", "eagle": "alt", "altGroup": "Cycling / Hiking / Swimming"},
  {"id": "dentistry", "name": "Dentistry", "usssp": "mb040", "pdf": "Dentistry.pdf"},
  {"id": "digital-technology", "name": "Digital Technology", "usssp": "mb154", "pdf": "Digital-Technology.pdf"},
  {"id": "disabilities-awareness", "name": "Disabilities Awareness", "usssp": "mb060", "pdf": "Disabilities-Awareness.pdf"},
  {"id": "dog-care", "name": "Dog Care", "usssp": "mb041", "pdf": "Dog-Care.pdf"},
  {"id": "drafting", "name": "Drafting", "usssp": "mb042", "pdf": "Drafting.pdf"},
  {"id": "electricity", "name": "Electricity", "usssp": "mb043", "pdf": "Electricity.pdf"},
  {"id": "electronics", "name": "Electronics", "usssp": "mb044", "pdf": "Electronics.pdf"},
  {"id": "emergency-preparedness", "name": "Emergency Preparedness", "usssp": "mb006", "pdf": "Emergency-Preparedness.pdf", "eagle": "alt", "altGroup": "Emergency Preparedness / Lifesaving"},
  {"id": "energy", "name": "Energy", "usssp": "mb045", "pdf": "Energy.pdf"},
  {"id": "engineering", "name": "Engineering", "usssp": "mb046", "pdf": "Engineering.pdf"},
  {"id": "entrepreneurship", "name": "Entrepreneurship", "usssp": "mb134", "pdf": "Entrepreneurship.pdf"},
  {"id": "environmental-science", "name": "Environmental Science", "usssp": "mb007", "pdf": "Environmental-Science.pdf", "eagle": "alt", "altGroup": "Environmental Science / Sustainability"},
  {"id": "exploration", "name": "Exploration", "usssp": "mb159", "pdf": "Exploration.pdf"},
  {"id": "family-life", "name": "Family Life", "usssp": "mb129", "pdf": "Family-Life.pdf", "eagle": "required"},
  {"id": "farm-mechanics", "name": "Farm Mechanics", "usssp": "mb048", "pdf": "Farm-Mechanics.pdf"},
  {"id": "fingerprinting", "name": "Fingerprinting", "usssp": "mb049", "pdf": "Fingerprinting.pdf"},
  {"id": "fire-safety", "name": "Fire Safety", "usssp": "mb050", "pdf": "Fire-Safety.pdf"},
  {"id": "first-aid", "name": "First Aid", "usssp": "mb008", "pdf": "First-Aid.pdf", "eagle": "required"},
  {"id": "fish-and-wildlife-management", "name": "Fish and Wildlife Management", "usssp": "mb051", "pdf": "Fish-and-Wildlife-Management.pdf"},
  {"id": "fishing", "name": "Fishing", "usssp": "mb052", "pdf": "Fishing.pdf"},
  {"id": "fly-fishing", "name": "Fly Fishing", "usssp": "mb136", "pdf": "Fly-Fishing.pdf"},
  {"id": "forestry", "name": "Forestry", "usssp": "mb054", "pdf": "Forestry.pdf"},
  {"id": "game-design", "name": "Game Design", "usssp": "mb151", "pdf": "Game-Design.pdf"},
  {"id": "gardening", "name": "Gardening", "usssp": "mb055", "pdf": "Gardening.pdf"},
  {"id": "genealogy", "name": "Genealogy", "usssp": "mb056", "pdf": "Genealogy.pdf"},
  {"id": "geocaching", "name": "Geocaching", "usssp": "mb145", "pdf": "geocaching.pdf"},
  {"id": "geology", "name": "Geology", "usssp": "mb058", "pdf": "Geology.pdf"},
  {"id": "golf", "name": "Golf", "usssp": "mb059", "pdf": "Golf.pdf"},
  {"id": "graphic-arts", "name": "Graphic Arts", "usssp": "mb122", "pdf": "Graphic-Arts.pdf"},
  {"id": "health-care-professions", "name": "Health Care Professions", "usssp": "mb161", "pdf": "Health-Care-Professions.pdf"},
  {"id": "hiking", "name": "Hiking", "usssp": "mb061", "pdf": "Hiking.pdf", "eagle": "alt", "altGroup": "Cycling / Hiking / Swimming"},
  {"id": "home-repairs", "name": "Home Repairs", "usssp": "mb062", "pdf": "Home-Repairs.pdf"},
  {"id": "horsemanship", "name": "Horsemanship", "usssp": "mb063", "pdf": "Horsemanship.pdf"},
  {"id": "indian-lore", "name": "Indian Lore", "usssp": "mb064", "pdf": "Indian-Lore.pdf"},
  {"id": "insect-study", "name": "Insect Study", "usssp": "mb065", "pdf": "Insect-Study.pdf"},
  {"id": "inventing", "name": "Inventing", "usssp": "mb144", "pdf": "Inventing.pdf"},
  {"id": "journalism", "name": "Journalism", "usssp": "mb066", "pdf": "Journalism.pdf"},
  {"id": "kayaking", "name": "Kayaking", "usssp": "mb149", "pdf": "Kayaking.pdf"},
  {"id": "landscape-architecture", "name": "Landscape Architecture", "usssp": "mb067", "pdf": "Landscape-Architecture.pdf"},
  {"id": "law", "name": "Law", "usssp": "mb068", "pdf": "Law.pdf"},
  {"id": "leatherwork", "name": "Leatherwork", "usssp": "mb069", "pdf": "Leatherwork.pdf"},
  {"id": "lifesaving", "name": "Lifesaving", "usssp": "mb009", "pdf": "Lifesaving.pdf", "eagle": "alt", "altGroup": "Emergency Preparedness / Lifesaving"},
  {"id": "mammal-study", "name": "Mammal Study", "usssp": "mb071", "pdf": "Mammal-Study.pdf"},
  {"id": "medicine", "name": "Medicine", "usssp": "mb130", "retired": "Retired 2025 — replaced by Health Care Professions"},
  {"id": "metalwork", "name": "Metalwork", "usssp": "mb074", "pdf": "Metalwork.pdf"},
  {"id": "mining-in-society", "name": "Mining in Society", "usssp": "mb155", "pdf": "Mining-in-Society.pdf"},
  {"id": "model-design-and-building", "name": "Model Design and Building", "usssp": "mb075", "pdf": "Model-Design-and-Building.pdf"},
  {"id": "motorboating", "name": "Motorboating", "usssp": "mb076", "pdf": "Motorboating.pdf"},
  {"id": "moviemaking", "name": "Moviemaking", "usssp": "mb156", "pdf": "Moviemaking.pdf"},
  {"id": "music", "name": "Music", "usssp": "mb077", "pdf": "Music.pdf"},
  {"id": "nature", "name": "Nature", "usssp": "mb078", "pdf": "Nature.pdf"},
  {"id": "nuclear-science", "name": "Nuclear Science", "usssp": "mb024", "pdf": "Nuclear-Science.pdf"},
  {"id": "oceanography", "name": "Oceanography", "usssp": "mb079", "pdf": "Oceanography.pdf"},
  {"id": "orienteering", "name": "Orienteering", "usssp": "mb080", "pdf": "Orienteering.pdf"},
  {"id": "painting", "name": "Painting", "usssp": "mb081", "pdf": "Painting.pdf"},
  {"id": "personal-fitness", "name": "Personal Fitness", "usssp": "mb010", "pdf": "Personal-Fitness.pdf", "eagle": "required"},
  {"id": "personal-management", "name": "Personal Management", "usssp": "mb011", "pdf": "Personal-Management.pdf", "eagle": "required"},
  {"id": "pets", "name": "Pets", "usssp": "mb082", "pdf": "Pets.pdf"},
  {"id": "photography", "name": "Photography", "usssp": "mb083", "pdf": "Photography.pdf"},
  {"id": "pioneering", "name": "Pioneering", "usssp": "mb084", "pdf": "Pioneering.pdf"},
  {"id": "plant-science", "name": "Plant Science", "usssp": "mb085", "pdf": "Plant-Science.pdf"},
  {"id": "plumbing", "name": "Plumbing", "usssp": "mb086", "pdf": "Plumbing.pdf"},
  {"id": "pottery", "name": "Pottery", "usssp": "mb087", "pdf": "Pottery.pdf"},
  {"id": "programming", "name": "Programming", "usssp": "mb153", "pdf": "Programming.pdf"},
  {"id": "public-health", "name": "Public Health", "usssp": "mb089", "pdf": "Public-Health.pdf"},
  {"id": "public-speaking", "name": "Public Speaking", "usssp": "mb090", "pdf": "Public-Speaking.pdf"},
  {"id": "pulp-and-paper", "name": "Pulp and Paper", "usssp": "mb091", "pdf": "Pulp-and-Paper.pdf"},
  {"id": "radio", "name": "Radio", "usssp": "mb093", "pdf": "Radio.pdf"},
  {"id": "railroading", "name": "Railroading", "usssp": "mb094", "pdf": "Railroading.pdf"},
  {"id": "reading", "name": "Reading", "usssp": "mb095", "pdf": "Reading.pdf"},
  {"id": "reptile-and-amphibian-study", "name": "Reptile and Amphibian Study", "usssp": "mb096", "pdf": "Reptile-and-Amphibian-Study.pdf"},
  {"id": "rifle-shooting", "name": "Rifle Shooting", "usssp": "mb123", "pdf": "Rifle-Shooting.pdf"},
  {"id": "robotics", "name": "Robotics", "usssp": "mb146", "pdf": "Robotics.pdf"},
  {"id": "rowing", "name": "Rowing", "usssp": "mb098", "pdf": "Rowing.pdf"},
  {"id": "safety", "name": "Safety", "usssp": "mb012", "pdf": "Safety.pdf"},
  {"id": "salesmanship", "name": "Salesmanship", "usssp": "mb099", "pdf": "Salesmanship.pdf"},
  {"id": "scholarship", "name": "Scholarship", "usssp": "mb100", "pdf": "Scholarship.pdf"},
  {"id": "scouting-heritage", "name": "Scouting Heritage", "usssp": "mb143", "pdf": "Scouting-Heritage.pdf"},
  {"id": "scuba-diving", "name": "Scuba Diving", "usssp": "mb138", "pdf": "Scuba-Diving.pdf"},
  {"id": "sculpture", "name": "Sculpture", "usssp": "mb101", "pdf": "Sculpture.pdf"},
  {"id": "search-and-rescue", "name": "Search and Rescue", "usssp": "mb150", "pdf": "Search-and-Rescue.pdf"},
  {"id": "shotgun-shooting", "name": "Shotgun Shooting", "usssp": "mb124", "pdf": "Shotgun-Shooting.pdf"},
  {"id": "signs-signals-and-codes", "name": "Signs, Signals, and Codes", "usssp": "mb157", "pdf": "Signs-Signals-and-Codes.pdf"},
  {"id": "skating", "name": "Skating", "usssp": "mb103", "pdf": "Skating.pdf"},
  {"id": "small-boat-sailing", "name": "Small-Boat Sailing", "usssp": "mb105", "pdf": "Small-Boat-Sailing.pdf"},
  {"id": "snow-sports", "name": "Snow Sports", "usssp": "mb135", "pdf": "Snow-Sports.pdf"},
  {"id": "soil-and-water-conservation", "name": "Soil and Water Conservation", "usssp": "mb106", "pdf": "Soil-and-Water-Conservation.pdf"},
  {"id": "space-exploration", "name": "Space Exploration", "usssp": "mb107", "pdf": "Space-Exploration.pdf"},
  {"id": "sports", "name": "Sports", "usssp": "mb013", "pdf": "Sports.pdf"},
  {"id": "stamp-collecting", "name": "Stamp Collecting", "usssp": "mb108", "pdf": "Stamp-Collecting.pdf"},
  {"id": "surveying", "name": "Surveying", "usssp": "mb109", "pdf": "Surveying.pdf"},
  {"id": "sustainability", "name": "Sustainability", "usssp": "mb152", "pdf": "Sustainability.pdf", "eagle": "alt", "altGroup": "Environmental Science / Sustainability"},
  {"id": "swimming", "name": "Swimming", "usssp": "mb014", "pdf": "Swimming.pdf", "eagle": "alt", "altGroup": "Cycling / Hiking / Swimming"},
  {"id": "textile", "name": "Textile", "usssp": "mb110", "pdf": "Textile.pdf"},
  {"id": "theater", "name": "Theater", "usssp": "mb111", "pdf": "Theater.pdf"},
  {"id": "traffic-safety", "name": "Traffic Safety", "usssp": "mb112", "pdf": "Traffic-Safety.pdf"},
  {"id": "truck-transportation", "name": "Truck Transportation", "usssp": "mb113", "pdf": "Truck-Transportation.pdf"},
  {"id": "veterinary-medicine", "name": "Veterinary Medicine", "usssp": "mb114", "pdf": "Veterinary-Medicine.pdf"},
  {"id": "water-sports", "name": "Water Sports", "usssp": "mb115", "pdf": "Water-Sports.pdf"},
  {"id": "weather", "name": "Weather", "usssp": "mb116", "pdf": "Weather.pdf"},
  {"id": "welding", "name": "Welding", "usssp": "mb148", "pdf": "Welding.pdf"},
  {"id": "whitewater", "name": "Whitewater", "usssp": "mb125", "pdf": "Whitewater.pdf"},
  {"id": "wilderness-survival", "name": "Wilderness Survival", "usssp": "mb117", "pdf": "Wilderness-Survival.pdf"},
  {"id": "wood-carving", "name": "Wood Carving", "usssp": "mb118", "pdf": "Wood-Carving.pdf"},
  {"id": "woodwork", "name": "Woodwork", "usssp": "mb119", "pdf": "Woodwork.pdf"}
];
