/* Priyaan Hub — catalog of every Scouting America merit badge (139, as listed by the U.S. Scouting Service Project, Sept 2026).
   One badge per line so it is easy to edit. `pdf` is the file name of the free USSSP merit badge workbook:
   online at MB.workbookBase + pdf, or offline at badges/pdf/<pdf> after running `node fetch_workbooks.js`.
   USSSP terms allow local personal/Scouting use of the workbooks but not electronic redistribution — that is why the
   PDFs are downloaded to your device instead of being committed to this repository. */
var MB = window.MB = window.MB || {};   // `var` so this also loads in Node (fetch_workbooks.js)
MB.workbookBase = 'http://usscouts.org/mb/worksheets/';           // + pdf
MB.requirementsBase = 'http://usscouts.org/mb/';                   // + usssp + '.asp'  (requirements text)
MB.officialBase = 'https://www.scouting.org/merit-badges/';        // + id + '/'       (Scouting America page)
MB.localBase = 'badges/pdf/';                                       // offline copies
MB.CATEGORIES = ["Aquatics", "Arts & Media", "Citizenship & Life Skills", "Health & Safety", "Hobbies & Animals", "Nature & Environment", "Outdoors & Camping", "Science & Technology", "Sports & Fitness", "Trades & Business"];
MB.EAGLE = { required: ['Camping','Citizenship in the Community','Citizenship in the Nation','Citizenship in Society','Citizenship in the World','Communication','Cooking','Family Life','First Aid','Personal Fitness','Personal Management'],
  pickOne: [['Cycling','Hiking','Swimming'], ['Emergency Preparedness','Lifesaving'], ['Environmental Science','Sustainability']], electives: 7, total: 21 };
MB.CATALOG = [
  {"id": "american-business", "name": "American Business", "emoji": "💼", "cat": "Trades & Business", "usssp": "mb015", "pdf": "American-Business.pdf"},
  {"id": "american-cultures", "name": "American Cultures", "emoji": "🌎", "cat": "Citizenship & Life Skills", "usssp": "mb017", "pdf": "American-Cultures.pdf"},
  {"id": "american-heritage", "name": "American Heritage", "emoji": "🗽", "cat": "Citizenship & Life Skills", "usssp": "mb016", "pdf": "American-Heritage.pdf"},
  {"id": "american-labor", "name": "American Labor", "emoji": "👷", "cat": "Citizenship & Life Skills", "usssp": "mb121", "pdf": "American-Labor.pdf"},
  {"id": "animal-science", "name": "Animal Science", "emoji": "🐄", "cat": "Hobbies & Animals", "usssp": "mb018", "pdf": "Animal-Science.pdf"},
  {"id": "animation", "name": "Animation", "emoji": "🎞️", "cat": "Arts & Media", "usssp": "mb158", "pdf": "Animation.pdf"},
  {"id": "archaeology", "name": "Archaeology", "emoji": "🦴", "cat": "Science & Technology", "usssp": "mb132", "pdf": "Archaeology.pdf"},
  {"id": "archery", "name": "Archery", "emoji": "🏹", "cat": "Outdoors & Camping", "usssp": "mb019", "pdf": "Archery.pdf"},
  {"id": "architecture", "name": "Architecture", "emoji": "🏛️", "cat": "Trades & Business", "usssp": "mb020", "pdf": "Architecture.pdf"},
  {"id": "art", "name": "Art", "emoji": "🎨", "cat": "Arts & Media", "usssp": "mb021", "pdf": "Art.pdf"},
  {"id": "astronomy", "name": "Astronomy", "emoji": "🔭", "cat": "Science & Technology", "usssp": "mb022", "pdf": "Astronomy.pdf"},
  {"id": "athletics", "name": "Athletics", "emoji": "🏃", "cat": "Sports & Fitness", "usssp": "mb023", "pdf": "Athletics.pdf"},
  {"id": "automotive-maintenance", "name": "Automotive Maintenance", "emoji": "🚗", "cat": "Trades & Business", "usssp": "mb127", "pdf": "Automotive-Maintenance.pdf"},
  {"id": "aviation", "name": "Aviation", "emoji": "✈️", "cat": "Science & Technology", "usssp": "mb025", "pdf": "Aviation.pdf"},
  {"id": "backpacking", "name": "Backpacking", "emoji": "🎒", "cat": "Outdoors & Camping", "usssp": "mb026", "pdf": "Backpacking.pdf"},
  {"id": "basketry", "name": "Basketry", "emoji": "🧺", "cat": "Arts & Media", "usssp": "mb027", "pdf": "Basketry.pdf"},
  {"id": "bird-study", "name": "Bird Study", "emoji": "🐦", "cat": "Nature & Environment", "usssp": "mb029", "pdf": "Bird-Study.pdf"},
  {"id": "bugling", "name": "Bugling", "emoji": "🎺", "cat": "Arts & Media", "usssp": "mb032", "pdf": "Bugling.pdf"},
  {"id": "camping", "name": "Camping", "emoji": "⛺", "cat": "Outdoors & Camping", "usssp": "mb001", "pdf": "Camping.pdf", "eagle": "required"},
  {"id": "canoeing", "name": "Canoeing", "emoji": "🛶", "cat": "Aquatics", "usssp": "mb033", "pdf": "Canoeing.pdf"},
  {"id": "chemistry", "name": "Chemistry", "emoji": "⚗️", "cat": "Science & Technology", "usssp": "mb034", "pdf": "Chemistry.pdf"},
  {"id": "chess", "name": "Chess", "emoji": "♟️", "cat": "Hobbies & Animals", "usssp": "mb147", "pdf": "Chess.pdf"},
  {"id": "citizenship-in-society", "name": "Citizenship in Society", "emoji": "🤝", "cat": "Citizenship & Life Skills", "usssp": "mb160", "pdf": "Citizenship-in-Society.pdf", "eagle": "required", "note": "Added 2022"},
  {"id": "citizenship-in-the-community", "name": "Citizenship in the Community", "emoji": "🏘️", "cat": "Citizenship & Life Skills", "usssp": "mb002", "pdf": "Citizenship-in-the-Community.pdf", "eagle": "required"},
  {"id": "citizenship-in-the-nation", "name": "Citizenship in the Nation", "emoji": "🇺🇸", "cat": "Citizenship & Life Skills", "usssp": "mb003", "pdf": "Citizenship-in-the-Nation.pdf", "eagle": "required"},
  {"id": "citizenship-in-the-world", "name": "Citizenship in the World", "emoji": "🌍", "cat": "Citizenship & Life Skills", "usssp": "mb004", "pdf": "Citizenship-in-the-World.pdf", "eagle": "required"},
  {"id": "climbing", "name": "Climbing", "emoji": "🧗", "cat": "Outdoors & Camping", "usssp": "mb133", "pdf": "Climbing.pdf"},
  {"id": "coin-collecting", "name": "Coin Collecting", "emoji": "🪙", "cat": "Hobbies & Animals", "usssp": "mb035", "pdf": "Coin-Collecting.pdf"},
  {"id": "collections", "name": "Collections", "emoji": "🗃️", "cat": "Hobbies & Animals", "usssp": "mb128", "pdf": "Collections.pdf"},
  {"id": "communication", "name": "Communication", "emoji": "🗣️", "cat": "Citizenship & Life Skills", "usssp": "mb005", "pdf": "Communication.pdf", "eagle": "required"},
  {"id": "composite-materials", "name": "Composite Materials", "emoji": "🧪", "cat": "Science & Technology", "usssp": "mb137", "pdf": "Composite-Materials.pdf"},
  {"id": "cooking", "name": "Cooking", "emoji": "🍳", "cat": "Citizenship & Life Skills", "usssp": "mb038", "pdf": "Cooking.pdf", "eagle": "required"},
  {"id": "crime-prevention", "name": "Crime Prevention", "emoji": "🚨", "cat": "Health & Safety", "usssp": "mb131", "pdf": "Crime-Prevention.pdf"},
  {"id": "cycling", "name": "Cycling", "emoji": "🚴", "cat": "Sports & Fitness", "usssp": "mb039", "pdf": "Cycling.pdf", "eagle": "alt", "altGroup": "Cycling / Hiking / Swimming"},
  {"id": "dentistry", "name": "Dentistry", "emoji": "🦷", "cat": "Health & Safety", "usssp": "mb040", "pdf": "Dentistry.pdf"},
  {"id": "digital-technology", "name": "Digital Technology", "emoji": "💻", "cat": "Science & Technology", "usssp": "mb154", "pdf": "Digital-Technology.pdf"},
  {"id": "disabilities-awareness", "name": "Disabilities Awareness", "emoji": "♿", "cat": "Citizenship & Life Skills", "usssp": "mb060", "pdf": "Disabilities-Awareness.pdf"},
  {"id": "dog-care", "name": "Dog Care", "emoji": "🐕", "cat": "Hobbies & Animals", "usssp": "mb041", "pdf": "Dog-Care.pdf"},
  {"id": "drafting", "name": "Drafting", "emoji": "📐", "cat": "Trades & Business", "usssp": "mb042", "pdf": "Drafting.pdf"},
  {"id": "electricity", "name": "Electricity", "emoji": "⚡", "cat": "Science & Technology", "usssp": "mb043", "pdf": "Electricity.pdf"},
  {"id": "electronics", "name": "Electronics", "emoji": "🔌", "cat": "Science & Technology", "usssp": "mb044", "pdf": "Electronics.pdf"},
  {"id": "emergency-preparedness", "name": "Emergency Preparedness", "emoji": "🚑", "cat": "Health & Safety", "usssp": "mb006", "pdf": "Emergency-Preparedness.pdf", "eagle": "alt", "altGroup": "Emergency Preparedness / Lifesaving"},
  {"id": "energy", "name": "Energy", "emoji": "🔋", "cat": "Science & Technology", "usssp": "mb045", "pdf": "Energy.pdf"},
  {"id": "engineering", "name": "Engineering", "emoji": "⚙️", "cat": "Science & Technology", "usssp": "mb046", "pdf": "Engineering.pdf"},
  {"id": "entrepreneurship", "name": "Entrepreneurship", "emoji": "💡", "cat": "Trades & Business", "usssp": "mb134", "pdf": "Entrepreneurship.pdf"},
  {"id": "environmental-science", "name": "Environmental Science", "emoji": "🌱", "cat": "Nature & Environment", "usssp": "mb007", "pdf": "Environmental-Science.pdf", "eagle": "alt", "altGroup": "Environmental Science / Sustainability"},
  {"id": "exploration", "name": "Exploration", "emoji": "🧭", "cat": "Outdoors & Camping", "usssp": "mb159", "pdf": "Exploration.pdf"},
  {"id": "family-life", "name": "Family Life", "emoji": "👨‍👩‍👧", "cat": "Citizenship & Life Skills", "usssp": "mb129", "pdf": "Family-Life.pdf", "eagle": "required"},
  {"id": "farm-mechanics", "name": "Farm Mechanics", "emoji": "🚜", "cat": "Trades & Business", "usssp": "mb048", "pdf": "Farm-Mechanics.pdf"},
  {"id": "fingerprinting", "name": "Fingerprinting", "emoji": "🔍", "cat": "Science & Technology", "usssp": "mb049", "pdf": "Fingerprinting.pdf"},
  {"id": "fire-safety", "name": "Fire Safety", "emoji": "🧯", "cat": "Health & Safety", "usssp": "mb050", "pdf": "Fire-Safety.pdf"},
  {"id": "first-aid", "name": "First Aid", "emoji": "🩹", "cat": "Health & Safety", "usssp": "mb008", "pdf": "First-Aid.pdf", "eagle": "required"},
  {"id": "fish-and-wildlife-management", "name": "Fish and Wildlife Management", "emoji": "🦌", "cat": "Nature & Environment", "usssp": "mb051", "pdf": "Fish-and-Wildlife-Management.pdf"},
  {"id": "fishing", "name": "Fishing", "emoji": "🎣", "cat": "Outdoors & Camping", "usssp": "mb052", "pdf": "Fishing.pdf"},
  {"id": "fly-fishing", "name": "Fly Fishing", "emoji": "🪝", "cat": "Outdoors & Camping", "usssp": "mb136", "pdf": "Fly-Fishing.pdf"},
  {"id": "forestry", "name": "Forestry", "emoji": "🌲", "cat": "Nature & Environment", "usssp": "mb054", "pdf": "Forestry.pdf"},
  {"id": "game-design", "name": "Game Design", "emoji": "🎮", "cat": "Science & Technology", "usssp": "mb151", "pdf": "Game-Design.pdf"},
  {"id": "gardening", "name": "Gardening", "emoji": "🥕", "cat": "Nature & Environment", "usssp": "mb055", "pdf": "Gardening.pdf"},
  {"id": "genealogy", "name": "Genealogy", "emoji": "🌳", "cat": "Citizenship & Life Skills", "usssp": "mb056", "pdf": "Genealogy.pdf"},
  {"id": "geocaching", "name": "Geocaching", "emoji": "📍", "cat": "Outdoors & Camping", "usssp": "mb145", "pdf": "geocaching.pdf"},
  {"id": "geology", "name": "Geology", "emoji": "🪨", "cat": "Nature & Environment", "usssp": "mb058", "pdf": "Geology.pdf"},
  {"id": "golf", "name": "Golf", "emoji": "⛳", "cat": "Sports & Fitness", "usssp": "mb059", "pdf": "Golf.pdf"},
  {"id": "graphic-arts", "name": "Graphic Arts", "emoji": "🖨️", "cat": "Arts & Media", "usssp": "mb122", "pdf": "Graphic-Arts.pdf"},
  {"id": "health-care-professions", "name": "Health Care Professions", "emoji": "🩺", "cat": "Health & Safety", "usssp": "mb161", "pdf": "Health-Care-Professions.pdf"},
  {"id": "hiking", "name": "Hiking", "emoji": "🥾", "cat": "Outdoors & Camping", "usssp": "mb061", "pdf": "Hiking.pdf", "eagle": "alt", "altGroup": "Cycling / Hiking / Swimming"},
  {"id": "home-repairs", "name": "Home Repairs", "emoji": "🔨", "cat": "Trades & Business", "usssp": "mb062", "pdf": "Home-Repairs.pdf"},
  {"id": "horsemanship", "name": "Horsemanship", "emoji": "🐎", "cat": "Hobbies & Animals", "usssp": "mb063", "pdf": "Horsemanship.pdf"},
  {"id": "indian-lore", "name": "Indian Lore", "emoji": "🪶", "cat": "Citizenship & Life Skills", "usssp": "mb064", "pdf": "Indian-Lore.pdf"},
  {"id": "insect-study", "name": "Insect Study", "emoji": "🐞", "cat": "Nature & Environment", "usssp": "mb065", "pdf": "Insect-Study.pdf"},
  {"id": "inventing", "name": "Inventing", "emoji": "🧠", "cat": "Science & Technology", "usssp": "mb144", "pdf": "Inventing.pdf"},
  {"id": "journalism", "name": "Journalism", "emoji": "📰", "cat": "Arts & Media", "usssp": "mb066", "pdf": "Journalism.pdf"},
  {"id": "kayaking", "name": "Kayaking", "emoji": "🛶", "cat": "Aquatics", "usssp": "mb149", "pdf": "Kayaking.pdf"},
  {"id": "landscape-architecture", "name": "Landscape Architecture", "emoji": "🌷", "cat": "Trades & Business", "usssp": "mb067", "pdf": "Landscape-Architecture.pdf"},
  {"id": "law", "name": "Law", "emoji": "⚖️", "cat": "Citizenship & Life Skills", "usssp": "mb068", "pdf": "Law.pdf"},
  {"id": "leatherwork", "name": "Leatherwork", "emoji": "🧵", "cat": "Arts & Media", "usssp": "mb069", "pdf": "Leatherwork.pdf"},
  {"id": "lifesaving", "name": "Lifesaving", "emoji": "🛟", "cat": "Aquatics", "usssp": "mb009", "pdf": "Lifesaving.pdf", "eagle": "alt", "altGroup": "Emergency Preparedness / Lifesaving"},
  {"id": "mammal-study", "name": "Mammal Study", "emoji": "🦊", "cat": "Nature & Environment", "usssp": "mb071", "pdf": "Mammal-Study.pdf"},
  {"id": "medicine", "name": "Medicine", "emoji": "💊", "cat": "Health & Safety", "usssp": "mb130", "retired": "Retired 2025 — replaced by Health Care Professions"},
  {"id": "metalwork", "name": "Metalwork", "emoji": "🔩", "cat": "Trades & Business", "usssp": "mb074", "pdf": "Metalwork.pdf"},
  {"id": "mining-in-society", "name": "Mining in Society", "emoji": "⛏️", "cat": "Science & Technology", "usssp": "mb155", "pdf": "Mining-in-Society.pdf"},
  {"id": "model-design-and-building", "name": "Model Design and Building", "emoji": "🧱", "cat": "Arts & Media", "usssp": "mb075", "pdf": "Model-Design-and-Building.pdf"},
  {"id": "motorboating", "name": "Motorboating", "emoji": "🚤", "cat": "Aquatics", "usssp": "mb076", "pdf": "Motorboating.pdf"},
  {"id": "moviemaking", "name": "Moviemaking", "emoji": "🎬", "cat": "Arts & Media", "usssp": "mb156", "pdf": "Moviemaking.pdf"},
  {"id": "music", "name": "Music", "emoji": "🎵", "cat": "Arts & Media", "usssp": "mb077", "pdf": "Music.pdf"},
  {"id": "nature", "name": "Nature", "emoji": "🍃", "cat": "Nature & Environment", "usssp": "mb078", "pdf": "Nature.pdf"},
  {"id": "nuclear-science", "name": "Nuclear Science", "emoji": "☢️", "cat": "Science & Technology", "usssp": "mb024", "pdf": "Nuclear-Science.pdf"},
  {"id": "oceanography", "name": "Oceanography", "emoji": "🐚", "cat": "Nature & Environment", "usssp": "mb079", "pdf": "Oceanography.pdf"},
  {"id": "orienteering", "name": "Orienteering", "emoji": "🗺️", "cat": "Outdoors & Camping", "usssp": "mb080", "pdf": "Orienteering.pdf"},
  {"id": "painting", "name": "Painting", "emoji": "🖌️", "cat": "Arts & Media", "usssp": "mb081", "pdf": "Painting.pdf"},
  {"id": "personal-fitness", "name": "Personal Fitness", "emoji": "💪", "cat": "Sports & Fitness", "usssp": "mb010", "pdf": "Personal-Fitness.pdf", "eagle": "required"},
  {"id": "personal-management", "name": "Personal Management", "emoji": "💰", "cat": "Citizenship & Life Skills", "usssp": "mb011", "pdf": "Personal-Management.pdf", "eagle": "required"},
  {"id": "pets", "name": "Pets", "emoji": "🐹", "cat": "Hobbies & Animals", "usssp": "mb082", "pdf": "Pets.pdf"},
  {"id": "photography", "name": "Photography", "emoji": "📷", "cat": "Arts & Media", "usssp": "mb083", "pdf": "Photography.pdf"},
  {"id": "pioneering", "name": "Pioneering", "emoji": "🪢", "cat": "Outdoors & Camping", "usssp": "mb084", "pdf": "Pioneering.pdf"},
  {"id": "plant-science", "name": "Plant Science", "emoji": "🌿", "cat": "Nature & Environment", "usssp": "mb085", "pdf": "Plant-Science.pdf"},
  {"id": "plumbing", "name": "Plumbing", "emoji": "🚿", "cat": "Trades & Business", "usssp": "mb086", "pdf": "Plumbing.pdf"},
  {"id": "pottery", "name": "Pottery", "emoji": "🏺", "cat": "Arts & Media", "usssp": "mb087", "pdf": "Pottery.pdf"},
  {"id": "programming", "name": "Programming", "emoji": "🖥️", "cat": "Science & Technology", "usssp": "mb153", "pdf": "Programming.pdf"},
  {"id": "public-health", "name": "Public Health", "emoji": "🧼", "cat": "Health & Safety", "usssp": "mb089", "pdf": "Public-Health.pdf"},
  {"id": "public-speaking", "name": "Public Speaking", "emoji": "🎤", "cat": "Citizenship & Life Skills", "usssp": "mb090", "pdf": "Public-Speaking.pdf"},
  {"id": "pulp-and-paper", "name": "Pulp and Paper", "emoji": "📄", "cat": "Trades & Business", "usssp": "mb091", "pdf": "Pulp-and-Paper.pdf"},
  {"id": "radio", "name": "Radio", "emoji": "📻", "cat": "Science & Technology", "usssp": "mb093", "pdf": "Radio.pdf"},
  {"id": "railroading", "name": "Railroading", "emoji": "🚂", "cat": "Hobbies & Animals", "usssp": "mb094", "pdf": "Railroading.pdf"},
  {"id": "reading", "name": "Reading", "emoji": "📚", "cat": "Citizenship & Life Skills", "usssp": "mb095", "pdf": "Reading.pdf"},
  {"id": "reptile-and-amphibian-study", "name": "Reptile and Amphibian Study", "emoji": "🦎", "cat": "Nature & Environment", "usssp": "mb096", "pdf": "Reptile-and-Amphibian-Study.pdf"},
  {"id": "rifle-shooting", "name": "Rifle Shooting", "emoji": "🎯", "cat": "Outdoors & Camping", "usssp": "mb123", "pdf": "Rifle-Shooting.pdf"},
  {"id": "robotics", "name": "Robotics", "emoji": "🤖", "cat": "Science & Technology", "usssp": "mb146", "pdf": "Robotics.pdf"},
  {"id": "rowing", "name": "Rowing", "emoji": "🚣", "cat": "Aquatics", "usssp": "mb098", "pdf": "Rowing.pdf"},
  {"id": "safety", "name": "Safety", "emoji": "🦺", "cat": "Health & Safety", "usssp": "mb012", "pdf": "Safety.pdf"},
  {"id": "salesmanship", "name": "Salesmanship", "emoji": "🏷️", "cat": "Trades & Business", "usssp": "mb099", "pdf": "Salesmanship.pdf"},
  {"id": "scholarship", "name": "Scholarship", "emoji": "🎓", "cat": "Citizenship & Life Skills", "usssp": "mb100", "pdf": "Scholarship.pdf"},
  {"id": "scouting-heritage", "name": "Scouting Heritage", "emoji": "🎖️", "cat": "Citizenship & Life Skills", "usssp": "mb143", "pdf": "Scouting-Heritage.pdf"},
  {"id": "scuba-diving", "name": "Scuba Diving", "emoji": "🤿", "cat": "Aquatics", "usssp": "mb138", "pdf": "Scuba-Diving.pdf"},
  {"id": "sculpture", "name": "Sculpture", "emoji": "🗿", "cat": "Arts & Media", "usssp": "mb101", "pdf": "Sculpture.pdf"},
  {"id": "search-and-rescue", "name": "Search and Rescue", "emoji": "🆘", "cat": "Health & Safety", "usssp": "mb150", "pdf": "Search-and-Rescue.pdf"},
  {"id": "shotgun-shooting", "name": "Shotgun Shooting", "emoji": "🎯", "cat": "Outdoors & Camping", "usssp": "mb124", "pdf": "Shotgun-Shooting.pdf"},
  {"id": "signs-signals-and-codes", "name": "Signs, Signals, and Codes", "emoji": "🔣", "cat": "Science & Technology", "usssp": "mb157", "pdf": "Signs-Signals-and-Codes.pdf"},
  {"id": "skating", "name": "Skating", "emoji": "⛸️", "cat": "Sports & Fitness", "usssp": "mb103", "pdf": "Skating.pdf"},
  {"id": "small-boat-sailing", "name": "Small-Boat Sailing", "emoji": "⛵", "cat": "Aquatics", "usssp": "mb105", "pdf": "Small-Boat-Sailing.pdf"},
  {"id": "snow-sports", "name": "Snow Sports", "emoji": "🎿", "cat": "Sports & Fitness", "usssp": "mb135", "pdf": "Snow-Sports.pdf"},
  {"id": "soil-and-water-conservation", "name": "Soil and Water Conservation", "emoji": "💧", "cat": "Nature & Environment", "usssp": "mb106", "pdf": "Soil-and-Water-Conservation.pdf"},
  {"id": "space-exploration", "name": "Space Exploration", "emoji": "🚀", "cat": "Science & Technology", "usssp": "mb107", "pdf": "Space-Exploration.pdf"},
  {"id": "sports", "name": "Sports", "emoji": "⚽", "cat": "Sports & Fitness", "usssp": "mb013", "pdf": "Sports.pdf"},
  {"id": "stamp-collecting", "name": "Stamp Collecting", "emoji": "📮", "cat": "Hobbies & Animals", "usssp": "mb108", "pdf": "Stamp-Collecting.pdf"},
  {"id": "surveying", "name": "Surveying", "emoji": "📏", "cat": "Trades & Business", "usssp": "mb109", "pdf": "Surveying.pdf"},
  {"id": "sustainability", "name": "Sustainability", "emoji": "♻️", "cat": "Nature & Environment", "usssp": "mb152", "pdf": "Sustainability.pdf", "eagle": "alt", "altGroup": "Environmental Science / Sustainability"},
  {"id": "swimming", "name": "Swimming", "emoji": "🏊", "cat": "Aquatics", "usssp": "mb014", "pdf": "Swimming.pdf", "eagle": "alt", "altGroup": "Cycling / Hiking / Swimming"},
  {"id": "textile", "name": "Textile", "emoji": "🧶", "cat": "Arts & Media", "usssp": "mb110", "pdf": "Textile.pdf"},
  {"id": "theater", "name": "Theater", "emoji": "🎭", "cat": "Arts & Media", "usssp": "mb111", "pdf": "Theater.pdf"},
  {"id": "traffic-safety", "name": "Traffic Safety", "emoji": "🚦", "cat": "Health & Safety", "usssp": "mb112", "pdf": "Traffic-Safety.pdf"},
  {"id": "truck-transportation", "name": "Truck Transportation", "emoji": "🚚", "cat": "Trades & Business", "usssp": "mb113", "pdf": "Truck-Transportation.pdf"},
  {"id": "veterinary-medicine", "name": "Veterinary Medicine", "emoji": "🐾", "cat": "Hobbies & Animals", "usssp": "mb114", "pdf": "Veterinary-Medicine.pdf"},
  {"id": "water-sports", "name": "Water Sports", "emoji": "🏄", "cat": "Aquatics", "usssp": "mb115", "pdf": "Water-Sports.pdf"},
  {"id": "weather", "name": "Weather", "emoji": "🌤️", "cat": "Nature & Environment", "usssp": "mb116", "pdf": "Weather.pdf"},
  {"id": "welding", "name": "Welding", "emoji": "🔥", "cat": "Trades & Business", "usssp": "mb148", "pdf": "Welding.pdf"},
  {"id": "whitewater", "name": "Whitewater", "emoji": "🌊", "cat": "Aquatics", "usssp": "mb125", "pdf": "Whitewater.pdf"},
  {"id": "wilderness-survival", "name": "Wilderness Survival", "emoji": "🏕️", "cat": "Outdoors & Camping", "usssp": "mb117", "pdf": "Wilderness-Survival.pdf"},
  {"id": "wood-carving", "name": "Wood Carving", "emoji": "🪵", "cat": "Arts & Media", "usssp": "mb118", "pdf": "Wood-Carving.pdf"},
  {"id": "woodwork", "name": "Woodwork", "emoji": "🪚", "cat": "Trades & Business", "usssp": "mb119", "pdf": "Woodwork.pdf"}
];
