#!/usr/bin/env node
/* Download the free USSSP merit badge workbooks (one PDF per badge) into badges/pdf/ so the
   Merit Badges page can open them with no internet. Run:  node fetch_workbooks.js   (re-run to update)
   The PDFs are for local use on this device only — USSSP does not allow re-publishing them — so
   badges/pdf/*.pdf is ignored by git and only the tiny manifest of what you have is written. */
'use strict';
const fs = require('fs'), path = require('path'), http = require('http'), https = require('https');
const { execSync } = require('child_process');
global.window = {};
require('./badges_catalog.js');
const MB = global.window.MB;
const dir = path.join(__dirname, 'badges', 'pdf');
fs.mkdirSync(dir, { recursive: true });
const args = process.argv.slice(2);
const force = args.includes('--force');
const only = args.filter(a => !a.startsWith('--')).map(s => s.toLowerCase());

function get(url, redirects) {
  return new Promise((resolve, reject) => {
    const lib = url.startsWith('https') ? https : http;
    const req = lib.get(url, { headers: { 'User-Agent': 'Mozilla/5.0 (priyaan-hub fetch_workbooks)' }, timeout: 60000 }, res => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location && (redirects || 0) < 5) {
        res.resume(); return resolve(get(new URL(res.headers.location, url).href, (redirects || 0) + 1));
      }
      if (res.statusCode !== 200) { res.resume(); return reject(new Error('HTTP ' + res.statusCode)); }
      const chunks = []; res.on('data', c => chunks.push(c)); res.on('end', () => resolve(Buffer.concat(chunks))); res.on('error', reject);
    });
    req.on('timeout', () => req.destroy(new Error('timeout'))); req.on('error', reject);
  });
}
function writeManifest() {
  const have = fs.readdirSync(dir).filter(f => /\.pdf$/i.test(f)).sort();
  const js = '/* Generated by fetch_workbooks.js — which workbook PDFs are on this device. Not committed (skip-worktree). */\n' +
    'window.PH_LOCAL_PDFS = ' + JSON.stringify(have) + ';\n';
  fs.writeFileSync(path.join(dir, 'manifest.js'), js);
  try { execSync('git update-index --skip-worktree badges/pdf/manifest.js', { cwd: __dirname, stdio: 'ignore' }); } catch (e) { /* not a git checkout */ }
  return have.length;
}
(async () => {
  const todo = MB.CATALOG.filter(b => b.pdf && (!only.length || only.some(o => b.name.toLowerCase().includes(o) || b.id.includes(o))));
  let ok = 0, skipped = 0, failed = [];
  for (const b of todo) {
    const dest = path.join(dir, b.pdf);
    if (!force && fs.existsSync(dest) && fs.statSync(dest).size > 10000) { skipped++; continue; }
    const url = MB.workbookBase + b.pdf;
    try {
      const buf = await get(url);
      if (buf.length < 10000 || buf.slice(0, 4).toString() !== '%PDF') throw new Error('not a PDF (' + buf.length + ' bytes)');
      fs.writeFileSync(dest, buf); ok++;
      process.stdout.write(`✓ ${b.name} (${(buf.length / 1024).toFixed(0)} KB)\n`);
    } catch (e) { failed.push(b.name + ': ' + e.message); process.stdout.write(`✗ ${b.name}: ${e.message}\n`); }
  }
  const have = writeManifest();
  const bytes = fs.readdirSync(dir).filter(f => /\.pdf$/i.test(f)).reduce((n, f) => n + fs.statSync(path.join(dir, f)).size, 0);
  console.log(`\nDownloaded ${ok}, already had ${skipped}, failed ${failed.length}. ${have} workbooks in badges/pdf (${(bytes / 1048576).toFixed(0)} MB).`);
  if (failed.length) { console.log('Failed:\n  ' + failed.join('\n  ')); process.exitCode = 1; }
})();
