/* hindi_data.js — the Malhar vocabulary, kept out of the page so other pages (and the hub's search)
   can read it too. One entry per line: edit here to change what the flashcards teach.
     CHAPTERS: { id, cls, n, title, genre, author }
     CARDS:    { ch, hi, tr, en, hint }   — the card id is ch + ':' + hi */
var HINDI = (typeof window === 'object' ? (window.HINDI = window.HINDI || {}) : {});
HINDI.CHAPTERS = [ // { id, cls, n, title, genre, author }
  { id: 'c6-01', cls: 6, n: 1,  title: 'मातृभूमि', genre: 'कविता', author: 'सोहनलाल द्विवेदी' },
  { id: 'c6-02', cls: 6, n: 2,  title: 'गोल', genre: 'संस्मरण', author: 'मेजर ध्यानचंद' },
  { id: 'c6-03', cls: 6, n: 3,  title: 'पहली बूँद', genre: 'कविता', author: 'गोपालकृष्ण कौल' },
  { id: 'c6-04', cls: 6, n: 4,  title: 'हार की जीत', genre: 'कहानी', author: 'सुदर्शन' },
  { id: 'c6-05', cls: 6, n: 5,  title: 'रहीम के दोहे', genre: 'दोहा', author: 'अब्दुर्रहीम खानखाना' },
  { id: 'c6-06', cls: 6, n: 6,  title: 'मेरी माँ', genre: 'आत्मकथा', author: 'रामप्रसाद ‘बिस्मिल’' },
  { id: 'c6-07', cls: 6, n: 7,  title: 'जलाते चलो', genre: 'कविता', author: 'द्वारिका प्रसाद ‘माहेश्वरी’' },
  { id: 'c6-08', cls: 6, n: 8,  title: 'सत्रिया और बिहू नृत्य', genre: 'निबंध', author: 'जया मेहता' },
  { id: 'c6-09', cls: 6, n: 9,  title: 'मैया मैं नहिं माखन खायो', genre: 'पद', author: 'सूरदास' },
  { id: 'c6-10', cls: 6, n: 10, title: 'परीक्षा', genre: 'कहानी', author: 'प्रेमचंद' },
  { id: 'c6-11', cls: 6, n: 11, title: 'चेतक की वीरता', genre: 'कविता', author: 'श्यामनारायण पांडेय' },
  { id: 'c6-12', cls: 6, n: 12, title: 'हिंद महासागर में छोटा-सा हिंदुस्तान', genre: 'यात्रा वृत्तांत', author: 'रामधारी सिंह ‘दिनकर’' },
  { id: 'c6-13', cls: 6, n: 13, title: 'पेड़ की बात', genre: 'निबंध', author: 'जगदीशचंद्र बसु' },
  { id: 'c7-01', cls: 7, n: 1,  title: 'माँ, कह एक कहानी', genre: 'कविता', author: 'मैथिलीशरण गुप्त' },
  { id: 'c7-02', cls: 7, n: 2,  title: 'तीन बुद्धिमान', genre: 'लोककथा', author: '' },
  { id: 'c7-03', cls: 7, n: 3,  title: 'फूल और काँटा', genre: 'कविता', author: 'अयोध्यासिंह उपाध्याय ‘हरिऔध’' },
  { id: 'c7-04', cls: 7, n: 4,  title: 'पानी रे पानी', genre: 'निबंध', author: 'अनुपम मिश्र' },
  { id: 'c7-05', cls: 7, n: 5,  title: 'नहीं होना बीमार', genre: 'कहानी', author: 'स्वयं प्रकाश' },
  { id: 'c7-06', cls: 7, n: 6,  title: 'गिरिधर कविराय की कुंडलिया', genre: 'कुंडलिया', author: 'गिरिधर कविराय' },
  { id: 'c7-07', cls: 7, n: 7,  title: 'वर्षा-बहार', genre: 'कविता', author: 'मुकुटधर पांडेय' },
  { id: 'c7-08', cls: 7, n: 8,  title: 'बिरजू महाराज से साक्षात्कार', genre: 'साक्षात्कार', author: '' },
  { id: 'c7-09', cls: 7, n: 9,  title: 'चिड़िया', genre: 'कविता', author: 'आरसी प्रसाद सिंह' },
  { id: 'c7-10', cls: 7, n: 10, title: 'मीरा के पद', genre: 'पद', author: 'मीरा' }
];
HINDI.CARDS = [ // { ch, hi, tr, en, hint }   hi = Devanagari, tr = romanisation, en = short meaning, hint = Hindi gloss
  // ---- Class 6, 1: मातृभूमि ----
  { ch: 'c6-01', hi: 'मातृभूमि', tr: 'mātṛbhūmi', en: 'motherland', hint: 'जन्मभूमि' },
  { ch: 'c6-01', hi: 'सिंधु', tr: 'sindhu', en: 'ocean, sea', hint: 'समुद्र' },
  { ch: 'c6-01', hi: 'नत', tr: 'nat', en: 'bowed, bent low', hint: 'झुका हुआ' },
  { ch: 'c6-01', hi: 'चरण', tr: 'caraṇ', en: 'feet', hint: 'पैर' },
  { ch: 'c6-01', hi: 'त्रिवेणी', tr: 'triveṇī', en: 'meeting of three rivers', hint: 'तीन नदियों का संगम' },
  { ch: 'c6-01', hi: 'लहर', tr: 'lahar', en: 'wave', hint: 'मौज, तरंग' },
  { ch: 'c6-01', hi: 'छटा', tr: 'chaṭā', en: 'beauty, splendour', hint: 'शोभा, सुंदरता' },
  { ch: 'c6-01', hi: 'निराली', tr: 'nirālī', en: 'unique, wonderful', hint: 'अनोखी' },
  { ch: 'c6-01', hi: 'छहर', tr: 'chahar', en: 'to spread, scatter', hint: 'बिखरना, फैलना' },
  { ch: 'c6-01', hi: 'पुण्य-भूमि', tr: 'puṇya-bhūmi', en: 'holy land', hint: 'पवित्र भूमि' },
  { ch: 'c6-01', hi: 'स्वर्ण-भूमि', tr: 'svarṇ-bhūmi', en: 'golden land', hint: 'सोने की भूमि' },
  { ch: 'c6-01', hi: 'अमराइयाँ', tr: 'amarāiyā̃', en: 'mango groves', hint: 'आम के बाग' },
  { ch: 'c6-01', hi: 'मलय पवन', tr: 'malay pavan', en: 'fragrant southern breeze', hint: 'मलय पर्वत से आती सुगंधित हवा' },
  { ch: 'c6-01', hi: 'सँवारना', tr: 'sãvārnā', en: 'to adorn, groom', hint: 'सजाना' },
  { ch: 'c6-01', hi: 'रघुपति', tr: 'raghupati', en: 'Lord Rama', hint: 'श्रीराम' },
  { ch: 'c6-01', hi: 'वंशी', tr: 'vanśī', en: 'flute', hint: 'बाँसुरी' },
  { ch: 'c6-01', hi: 'पुनीत', tr: 'punīt', en: 'holy, sacred', hint: 'पवित्र' },
  { ch: 'c6-01', hi: 'सुयश', tr: 'suyaś', en: 'good fame', hint: 'अच्छी कीर्ति' },
  // ---- Class 6, 2: गोल ----
  { ch: 'c6-02', hi: 'संस्मरण', tr: 'sansmaraṇ', en: 'memoir', hint: 'यादों का लेखन' },
  { ch: 'c6-02', hi: 'धक्का-मुक्की', tr: 'dhakkā-mukkī', en: 'jostling, pushing', hint: 'धक्का देना' },
  { ch: 'c6-02', hi: 'नोंक-झोंक', tr: 'nõk-jhõk', en: 'bickering, squabble', hint: 'छोटी-सी कहा-सुनी' },
  { ch: 'c6-02', hi: 'मुकाबला', tr: 'muqāblā', en: 'match, contest', hint: 'प्रतियोगिता' },
  { ch: 'c6-02', hi: 'बदला', tr: 'badlā', en: 'revenge', hint: 'प्रतिशोध' },
  { ch: 'c6-02', hi: 'झटपट', tr: 'jhaṭpaṭ', en: 'quickly', hint: 'तुरंत, जल्दी से' },
  { ch: 'c6-02', hi: 'शर्मिंदा', tr: 'śarmindā', en: 'ashamed', hint: 'लज्जित' },
  { ch: 'c6-02', hi: 'लगन', tr: 'lagan', en: 'dedication', hint: 'निष्ठा' },
  { ch: 'c6-02', hi: 'साधना', tr: 'sādhnā', en: 'disciplined practice', hint: 'अभ्यास, तप' },
  { ch: 'c6-02', hi: 'खेल भावना', tr: 'khel bhāvnā', en: 'sportsmanship', hint: 'खेल का सच्चा भाव' },
  { ch: 'c6-02', hi: 'भर्ती', tr: 'bhartī', en: 'enrolment, recruitment', hint: 'दाखिला' },
  { ch: 'c6-02', hi: 'दिलचस्पी', tr: 'dilcaspī', en: 'interest', hint: 'रुचि' },
  { ch: 'c6-02', hi: 'छावनी', tr: 'chāvnī', en: 'army camp, cantonment', hint: 'सैनिकों के रहने का क्षेत्र' },
  { ch: 'c6-02', hi: 'नौसिखिया', tr: 'nausikhiyā', en: 'beginner, novice', hint: 'नया सीखने वाला' },
  { ch: 'c6-02', hi: 'निखार', tr: 'nikhār', en: 'polish, improvement', hint: 'सुधार, चमक' },
  { ch: 'c6-02', hi: 'तरक्की', tr: 'taraqqī', en: 'promotion, progress', hint: 'उन्नति' },
  { ch: 'c6-02', hi: 'जादूगर', tr: 'jādūgar', en: 'magician', hint: 'जादू करने वाला' },
  { ch: 'c6-02', hi: 'श्रेय', tr: 'śrey', en: 'credit (for a deed)', hint: 'किसी काम का यश' },
  // ---- Class 6, 3: पहली बूँद ----
  { ch: 'c6-03', hi: 'पावस', tr: 'pāvas', en: 'rainy season', hint: 'वर्षा ऋतु' },
  { ch: 'c6-03', hi: 'धरा', tr: 'dharā', en: 'earth', hint: 'धरती, पृथ्वी' },
  { ch: 'c6-03', hi: 'अंकुर', tr: 'aṅkur', en: 'sprout, shoot', hint: 'बीज से निकला नया पौधा' },
  { ch: 'c6-03', hi: 'अँगड़ाई', tr: 'ãgṛāī', en: 'a stretch (on waking)', hint: 'देह फैलाना' },
  { ch: 'c6-03', hi: 'अधर', tr: 'adhar', en: 'lip', hint: 'होंठ' },
  { ch: 'c6-03', hi: 'अमृत', tr: 'amṛt', en: 'nectar', hint: 'अमर करने वाला रस' },
  { ch: 'c6-03', hi: 'वसुंधरा', tr: 'vasundharā', en: 'the earth', hint: 'धरती' },
  { ch: 'c6-03', hi: 'रोमावलि', tr: 'romāvali', en: 'row of fine body hair', hint: 'रोओं की पंक्ति' },
  { ch: 'c6-03', hi: 'दूब', tr: 'dūb', en: 'soft grass', hint: 'घास' },
  { ch: 'c6-03', hi: 'पुलकना', tr: 'pulaknā', en: 'to thrill with joy', hint: 'आनंद से रोमांचित होना' },
  { ch: 'c6-03', hi: 'स्वर्णिम', tr: 'svarṇim', en: 'golden', hint: 'सुनहरा' },
  { ch: 'c6-03', hi: 'नगाड़ा', tr: 'nagāṛā', en: 'kettledrum', hint: 'बड़ा ढोल' },
  { ch: 'c6-03', hi: 'तरुणाई', tr: 'taruṇāī', en: 'youth', hint: 'जवानी' },
  { ch: 'c6-03', hi: 'अंबर', tr: 'ambar', en: 'sky', hint: 'आकाश' },
  { ch: 'c6-03', hi: 'जलधर', tr: 'jaldhar', en: 'cloud', hint: 'बादल' },
  { ch: 'c6-03', hi: 'अश्रु', tr: 'aśru', en: 'tear', hint: 'आँसू' },
  { ch: 'c6-03', hi: 'शस्य-श्यामला', tr: 'śasya-śyāmlā', en: 'green with crops', hint: 'फसलों से हरी-भरी' },
  // ---- Class 6, 4: हार की जीत ----
  { ch: 'c6-04', hi: 'अर्पण', tr: 'arpaṇ', en: 'offering, dedication', hint: 'भेंट, समर्पण' },
  { ch: 'c6-04', hi: 'खरहरा', tr: 'kharahrā', en: 'brush for grooming a horse', hint: 'घोड़े की सफ़ाई का ब्रश' },
  { ch: 'c6-04', hi: 'घृणा', tr: 'ghṛṇā', en: 'hatred, disgust', hint: 'नफ़रत' },
  { ch: 'c6-04', hi: 'कीर्ति', tr: 'kīrti', en: 'fame', hint: 'यश' },
  { ch: 'c6-04', hi: 'अधीर', tr: 'adhīr', en: 'impatient, restless', hint: 'बेचैन' },
  { ch: 'c6-04', hi: 'अभिलाषा', tr: 'abhilāṣā', en: 'longing, wish', hint: 'इच्छा' },
  { ch: 'c6-04', hi: 'अस्तबल', tr: 'astabal', en: 'stable (for horses)', hint: 'घुड़साल' },
  { ch: 'c6-04', hi: 'बाँका', tr: 'bā̃kā', en: 'handsome, dashing', hint: 'सजीला, सुंदर' },
  { ch: 'c6-04', hi: 'बाहुबल', tr: 'bāhubal', en: 'physical strength', hint: 'भुजाओं की ताकत' },
  { ch: 'c6-04', hi: 'रखवाली', tr: 'rakhvālī', en: 'guarding', hint: 'पहरा, देखभाल' },
  { ch: 'c6-04', hi: 'मिथ्या', tr: 'mithyā', en: 'false', hint: 'झूठ' },
  { ch: 'c6-04', hi: 'सहसा', tr: 'sahsā', en: 'suddenly', hint: 'अचानक' },
  { ch: 'c6-04', hi: 'अपाहिज', tr: 'apāhij', en: 'disabled, crippled', hint: 'विकलांग' },
  { ch: 'c6-04', hi: 'करुणा', tr: 'karuṇā', en: 'compassion, pity', hint: 'दया' },
  { ch: 'c6-04', hi: 'लगाम', tr: 'lagām', en: 'reins', hint: 'घोड़े की रास' },
  { ch: 'c6-04', hi: 'विस्मय', tr: 'vismay', en: 'astonishment', hint: 'आश्चर्य' },
  { ch: 'c6-04', hi: 'प्रयोजन', tr: 'prayojan', en: 'purpose', hint: 'उद्देश्य' },
  { ch: 'c6-04', hi: 'प्रकट', tr: 'prakaṭ', en: 'revealed, expressed', hint: 'ज़ाहिर' },
  // ---- Class 6, 5: रहीम के दोहे ----
  { ch: 'c6-05', hi: 'दोहा', tr: 'dohā', en: 'couplet (two-line verse)', hint: 'दो पंक्तियों का छंद' },
  { ch: 'c6-05', hi: 'लघु', tr: 'laghu', en: 'small', hint: 'छोटा' },
  { ch: 'c6-05', hi: 'तरुवर', tr: 'taruvar', en: 'tree', hint: 'पेड़, वृक्ष' },
  { ch: 'c6-05', hi: 'सरवर', tr: 'saravar', en: 'lake, pond', hint: 'सरोवर, तालाब' },
  { ch: 'c6-05', hi: 'संपति', tr: 'sampati', en: 'wealth', hint: 'संपत्ति, धन' },
  { ch: 'c6-05', hi: 'सुजान', tr: 'sujān', en: 'wise person', hint: 'सज्जन, बुद्धिमान' },
  { ch: 'c6-05', hi: 'चिटकाय', tr: 'ciṭkāy', en: 'snapping (with a jerk)', hint: 'झटके से तोड़ना' },
  { ch: 'c6-05', hi: 'गाँठ', tr: 'gā̃ṭh', en: 'knot', hint: 'बंधन' },
  { ch: 'c6-05', hi: 'बिनु', tr: 'binu', en: 'without', hint: 'बिना' },
  { ch: 'c6-05', hi: 'सून', tr: 'sūn', en: 'empty, worthless', hint: 'सूना, शून्य' },
  { ch: 'c6-05', hi: 'ऊबरै', tr: 'ūbarai', en: 'is saved, survives', hint: 'उबरता है, बचता है' },
  { ch: 'c6-05', hi: 'मानुष', tr: 'mānuṣ', en: 'human being', hint: 'मनुष्य' },
  { ch: 'c6-05', hi: 'बिपदा', tr: 'bipdā', en: 'calamity, hard times', hint: 'विपत्ति, मुसीबत' },
  { ch: 'c6-05', hi: 'जिह्वा', tr: 'jihvā', en: 'tongue', hint: 'जीभ' },
  { ch: 'c6-05', hi: 'बावरी', tr: 'bāvrī', en: 'crazy, mad', hint: 'पागल' },
  { ch: 'c6-05', hi: 'सरग', tr: 'sarag', en: 'heaven', hint: 'स्वर्ग' },
  { ch: 'c6-05', hi: 'कसौटी', tr: 'kasauṭī', en: 'touchstone, test', hint: 'परख, जाँच' },
  { ch: 'c6-05', hi: 'मीत', tr: 'mīt', en: 'friend', hint: 'मित्र' },
  // ---- Class 6, 6: मेरी माँ ----
  { ch: 'c6-06', hi: 'आत्मकथा', tr: 'ātmakathā', en: 'autobiography', hint: 'अपने जीवन की कहानी' },
  { ch: 'c6-06', hi: 'उत्साह', tr: 'utsāh', en: 'enthusiasm', hint: 'जोश' },
  { ch: 'c6-06', hi: 'दंड', tr: 'daṇḍ', en: 'punishment', hint: 'सज़ा' },
  { ch: 'c6-06', hi: 'साहस', tr: 'sāhas', en: 'courage', hint: 'हिम्मत' },
  { ch: 'c6-06', hi: 'अनुरोध', tr: 'anurodh', en: 'request', hint: 'आग्रह' },
  { ch: 'c6-06', hi: 'प्रोत्साहन', tr: 'protsāhan', en: 'encouragement', hint: 'बढ़ावा, हौसला' },
  { ch: 'c6-06', hi: 'दृढ़ता', tr: 'dṛṛhtā', en: 'firmness, resolve', hint: 'मज़बूती, अटलता' },
  { ch: 'c6-06', hi: 'संकल्प', tr: 'saṅkalp', en: 'resolve, vow', hint: 'दृढ़ निश्चय' },
  { ch: 'c6-06', hi: 'हस्ताक्षर', tr: 'hastākṣar', en: 'signature', hint: 'दस्तख़त' },
  { ch: 'c6-06', hi: 'कदापि', tr: 'kadāpi', en: 'never, by no means', hint: 'कभी नहीं' },
  { ch: 'c6-06', hi: 'नितांत', tr: 'nitānt', en: 'utterly, completely', hint: 'बिलकुल, पूर्णतः' },
  { ch: 'c6-06', hi: 'परिश्रम', tr: 'pariśram', en: 'hard work', hint: 'मेहनत' },
  { ch: 'c6-06', hi: 'प्रतिज्ञा', tr: 'pratigyā', en: 'vow, promise', hint: 'वचन, प्रण' },
  { ch: 'c6-06', hi: 'जननी', tr: 'jananī', en: 'mother', hint: 'माँ, माता' },
  { ch: 'c6-06', hi: 'ऋण', tr: 'ṛṇ', en: 'debt', hint: 'कर्ज़' },
  { ch: 'c6-06', hi: 'स्मरण', tr: 'smaraṇ', en: 'memory, remembering', hint: 'याद' },
  { ch: 'c6-06', hi: 'सांत्वना', tr: 'sāntvanā', en: 'consolation', hint: 'ढाढ़स, धीरज बँधाना' },
  { ch: 'c6-06', hi: 'सदैव', tr: 'sadaiv', en: 'always', hint: 'हमेशा' },
  // ---- Class 6, 7: जलाते चलो ----
  { ch: 'c6-07', hi: 'दिया', tr: 'diyā', en: 'earthen lamp', hint: 'दीपक' },
  { ch: 'c6-07', hi: 'स्नेह', tr: 'sneh', en: 'affection; oil for a lamp', hint: 'प्रेम; तेल' },
  { ch: 'c6-07', hi: 'निहित', tr: 'nihit', en: 'contained in, inherent', hint: 'छिपा हुआ, समाया हुआ' },
  { ch: 'c6-07', hi: 'अमावस', tr: 'amāvas', en: 'new-moon night', hint: 'अमावस्या, अँधेरी रात' },
  { ch: 'c6-07', hi: 'पूर्णिमा', tr: 'pūrṇimā', en: 'full-moon night', hint: 'पूरे चाँद की रात' },
  { ch: 'c6-07', hi: 'निशा', tr: 'niśā', en: 'night', hint: 'रात' },
  { ch: 'c6-07', hi: 'विद्युत', tr: 'vidyut', en: 'electricity', hint: 'बिजली' },
  { ch: 'c6-07', hi: 'तिमिर', tr: 'timir', en: 'darkness', hint: 'अंधकार' },
  { ch: 'c6-07', hi: 'चुनौती', tr: 'cunautī', en: 'challenge', hint: 'ललकार' },
  { ch: 'c6-07', hi: 'सरित', tr: 'sarit', en: 'river', hint: 'नदी' },
  { ch: 'c6-07', hi: 'निरंतर', tr: 'nirantar', en: 'continuously', hint: 'लगातार' },
  { ch: 'c6-07', hi: 'युग', tr: 'yug', en: 'era, age', hint: 'बहुत लंबा समय' },
  { ch: 'c6-07', hi: 'शिला', tr: 'śilā', en: 'rock, stone slab', hint: 'चट्टान, पत्थर' },
  { ch: 'c6-07', hi: 'अनगिनत', tr: 'anginat', en: 'countless', hint: 'असंख्य' },
  { ch: 'c6-07', hi: 'साक्षी', tr: 'sākṣī', en: 'witness', hint: 'गवाह' },
  { ch: 'c6-07', hi: 'ज्योति', tr: 'jyoti', en: 'flame, light', hint: 'लौ, प्रकाश' },
  { ch: 'c6-07', hi: 'उजेला', tr: 'ujelā', en: 'light, brightness', hint: 'उजाला, प्रकाश' },
  // ---- Class 6, 8: सत्रिया और बिहू नृत्य ----
  { ch: 'c6-08', hi: 'नृत्य', tr: 'nṛtya', en: 'dance', hint: 'नाच' },
  { ch: 'c6-08', hi: 'निबंध', tr: 'nibandh', en: 'essay', hint: 'लेख' },
  { ch: 'c6-08', hi: 'परंपरा', tr: 'paramparā', en: 'tradition', hint: 'रीति, प्रथा' },
  { ch: 'c6-08', hi: 'सगा', tr: 'sagā', en: 'real, blood-related', hint: 'अपना, खून का' },
  { ch: 'c6-08', hi: 'कल्पना', tr: 'kalpanā', en: 'imagination', hint: 'ख़याल, सोच' },
  { ch: 'c6-08', hi: 'ज़िक्र', tr: 'zikr', en: 'mention', hint: 'उल्लेख, चर्चा' },
  { ch: 'c6-08', hi: 'पेचीदा', tr: 'pecīdā', en: 'complicated', hint: 'जटिल, कठिन' },
  { ch: 'c6-08', hi: 'अनुमति', tr: 'anumati', en: 'permission', hint: 'इजाज़त' },
  { ch: 'c6-08', hi: 'समृद्ध', tr: 'samṛddh', en: 'rich, prosperous', hint: 'संपन्न, धनी' },
  { ch: 'c6-08', hi: 'कृषि', tr: 'kṛṣi', en: 'agriculture', hint: 'खेती' },
  { ch: 'c6-08', hi: 'उत्सव', tr: 'utsav', en: 'festival, celebration', hint: 'त्योहार, समारोह' },
  { ch: 'c6-08', hi: 'हतप्रभ', tr: 'hatprabh', en: 'stunned, dazed', hint: 'चकित, सन्न' },
  { ch: 'c6-08', hi: 'मंत्रमुग्ध', tr: 'mantramugdh', en: 'spellbound', hint: 'मोहित, मुग्ध' },
  { ch: 'c6-08', hi: 'आगमन', tr: 'āgaman', en: 'arrival', hint: 'आना' },
  { ch: 'c6-08', hi: 'वाद्ययंत्र', tr: 'vādyayantra', en: 'musical instrument', hint: 'बाजा' },
  { ch: 'c6-08', hi: 'पोशाक', tr: 'pośāk', en: 'costume, dress', hint: 'वेशभूषा, कपड़े' },
  { ch: 'c6-08', hi: 'लज़ीज़', tr: 'lazīz', en: 'delicious', hint: 'स्वादिष्ट' },
  { ch: 'c6-08', hi: 'साक्षात्कार', tr: 'sākṣātkār', en: 'interview', hint: 'भेंट-वार्ता' },
  // ---- Class 6, 9: मैया मैं नहिं माखन खायो (Braj) ----
  { ch: 'c6-09', hi: 'पद', tr: 'pad', en: 'devotional song, verse', hint: 'भक्ति गीत' },
  { ch: 'c6-09', hi: 'मैया', tr: 'maiyā', en: 'mother', hint: 'माँ' },
  { ch: 'c6-09', hi: 'नहिं', tr: 'nahĩ', en: 'not', hint: 'नहीं' },
  { ch: 'c6-09', hi: 'माखन', tr: 'mākhan', en: 'butter', hint: 'मक्खन' },
  { ch: 'c6-09', hi: 'भोर', tr: 'bhor', en: 'dawn', hint: 'सुबह, प्रातः' },
  { ch: 'c6-09', hi: 'पठायो', tr: 'paṭhāyo', en: 'sent', hint: 'भेजा' },
  { ch: 'c6-09', hi: 'पहर', tr: 'pahar', en: 'a watch of three hours', hint: 'तीन घंटे का समय' },
  { ch: 'c6-09', hi: 'बंसीवट', tr: 'bansīvaṭ', en: 'banyan where Krishna played the flute', hint: 'एक वट वृक्ष' },
  { ch: 'c6-09', hi: 'साँझ', tr: 'sā̃jh', en: 'evening', hint: 'शाम, संध्या' },
  { ch: 'c6-09', hi: 'बहियन', tr: 'bahiyan', en: 'arms', hint: 'बाँहें' },
  { ch: 'c6-09', hi: 'छीको', tr: 'chīko', en: 'hanging basket for food', hint: 'छींका, ऊँचा टँगा जाल' },
  { ch: 'c6-09', hi: 'बिधि', tr: 'bidhi', en: 'way, manner', hint: 'विधि, तरीका' },
  { ch: 'c6-09', hi: 'ग्वाल-बाल', tr: 'gvāl-bāl', en: 'cowherd boys', hint: 'गोप बालक' },
  { ch: 'c6-09', hi: 'बरबस', tr: 'barbas', en: 'forcibly', hint: 'ज़बरदस्ती' },
  { ch: 'c6-09', hi: 'भोरी', tr: 'bhorī', en: 'innocent, naive', hint: 'भोली' },
  { ch: 'c6-09', hi: 'हिय', tr: 'hiy', en: 'heart', hint: 'हृदय, दिल' },
  { ch: 'c6-09', hi: 'लकुटि', tr: 'lakuṭi', en: 'small stick', hint: 'लाठी' },
  { ch: 'c6-09', hi: 'बिहँसि', tr: 'bihãsi', en: 'smiling, laughing', hint: 'हँसकर' },
  // ---- Class 6, 10: परीक्षा ----
  { ch: 'c6-10', hi: 'रियासत', tr: 'riyāsat', en: 'princely state', hint: 'राज्य' },
  { ch: 'c6-10', hi: 'दीवान', tr: 'dīvān', en: 'chief minister of a state', hint: 'मंत्री, प्रधान अधिकारी' },
  { ch: 'c6-10', hi: 'विनय', tr: 'vinay', en: 'humble request', hint: 'प्रार्थना, निवेदन' },
  { ch: 'c6-10', hi: 'नेकनामी', tr: 'neknāmī', en: 'good reputation', hint: 'अच्छा नाम, यश' },
  { ch: 'c6-10', hi: 'विज्ञापन', tr: 'vigyāpan', en: 'advertisement', hint: 'इश्तहार' },
  { ch: 'c6-10', hi: 'सुयोग्य', tr: 'suyogya', en: 'well-qualified', hint: 'बहुत योग्य' },
  { ch: 'c6-10', hi: 'उम्मीदवार', tr: 'ummīdvār', en: 'candidate', hint: 'प्रत्याशी' },
  { ch: 'c6-10', hi: 'कर्तव्य', tr: 'kartavya', en: 'duty', hint: 'फ़र्ज़' },
  { ch: 'c6-10', hi: 'तहलका', tr: 'tahalkā', en: 'sensation, uproar', hint: 'हलचल, खलबली' },
  { ch: 'c6-10', hi: 'नसीब', tr: 'nasīb', en: 'fate, luck', hint: 'भाग्य, किस्मत' },
  { ch: 'c6-10', hi: 'सादगी', tr: 'sādgī', en: 'simplicity', hint: 'सरलता' },
  { ch: 'c6-10', hi: 'सदाचार', tr: 'sadācār', en: 'good conduct', hint: 'अच्छा आचरण' },
  { ch: 'c6-10', hi: 'जौहरी', tr: 'jauharī', en: 'jeweller, judge of gems', hint: 'रत्नों का पारखी' },
  { ch: 'c6-10', hi: 'पथिक', tr: 'pathik', en: 'traveller', hint: 'राहगीर, यात्री' },
  { ch: 'c6-10', hi: 'सहानुभूति', tr: 'sahānubhūti', en: 'sympathy', hint: 'हमदर्दी' },
  { ch: 'c6-10', hi: 'उदारता', tr: 'udārtā', en: 'generosity', hint: 'बड़ा दिल, दानशीलता' },
  { ch: 'c6-10', hi: 'अकस्मात', tr: 'akasmāt', en: 'all of a sudden', hint: 'अचानक' },
  { ch: 'c6-10', hi: 'आत्मबल', tr: 'ātmabal', en: 'inner strength', hint: 'मनोबल' },
  // ---- Class 6, 11: चेतक की वीरता ----
  { ch: 'c6-11', hi: 'रण', tr: 'raṇ', en: 'battle', hint: 'युद्ध' },
  { ch: 'c6-11', hi: 'चौकड़ी', tr: 'caukṛī', en: 'gallop, bound', hint: 'छलाँग, कुलाँच' },
  { ch: 'c6-11', hi: 'कोड़ा', tr: 'koṛā', en: 'whip', hint: 'चाबुक' },
  { ch: 'c6-11', hi: 'अरि', tr: 'ari', en: 'enemy', hint: 'शत्रु' },
  { ch: 'c6-11', hi: 'मस्तक', tr: 'mastak', en: 'forehead, head', hint: 'माथा' },
  { ch: 'c6-11', hi: 'तनिक', tr: 'tanik', en: 'a little, slightly', hint: 'थोड़ा' },
  { ch: 'c6-11', hi: 'बाग', tr: 'bāg', en: 'rein (of a horse)', hint: 'लगाम' },
  { ch: 'c6-11', hi: 'पुतली', tr: 'putlī', en: 'pupil of the eye', hint: 'आँख की पुतली' },
  { ch: 'c6-11', hi: 'कौशल', tr: 'kauśal', en: 'skill', hint: 'निपुणता' },
  { ch: 'c6-11', hi: 'भाला', tr: 'bhālā', en: 'spear', hint: 'बरछा' },
  { ch: 'c6-11', hi: 'निर्भीक', tr: 'nirbhīk', en: 'fearless', hint: 'निडर' },
  { ch: 'c6-11', hi: 'सरपट', tr: 'sarpaṭ', en: 'at full gallop', hint: 'बहुत तेज़ दौड़' },
  { ch: 'c6-11', hi: 'करवाल', tr: 'karvāl', en: 'sword', hint: 'तलवार' },
  { ch: 'c6-11', hi: 'विकराल', tr: 'vikarāl', en: 'terrifying, monstrous', hint: 'भयानक' },
  { ch: 'c6-11', hi: 'बज्र', tr: 'bajra', en: 'thunderbolt', hint: 'वज्र, बिजली' },
  { ch: 'c6-11', hi: 'निषंग', tr: 'niṣaṅg', en: 'quiver (for arrows)', hint: 'तीर रखने का तरकश' },
  { ch: 'c6-11', hi: 'हय', tr: 'hay', en: 'horse', hint: 'घोड़ा' },
  // ---- Class 6, 12: हिंद महासागर में छोटा-सा हिंदुस्तान ----
  { ch: 'c6-12', hi: 'यात्रा वृत्तांत', tr: 'yātrā vṛttānt', en: 'travelogue', hint: 'यात्रा का विवरण' },
  { ch: 'c6-12', hi: 'रवाना', tr: 'ravānā', en: 'set out, departed', hint: 'प्रस्थान' },
  { ch: 'c6-12', hi: 'अतएव', tr: 'ataev', en: 'therefore', hint: 'इसलिए' },
  { ch: 'c6-12', hi: 'सर्वत्र', tr: 'sarvatra', en: 'everywhere', hint: 'हर जगह' },
  { ch: 'c6-12', hi: 'पर्यटक', tr: 'paryaṭak', en: 'tourist', hint: 'सैलानी' },
  { ch: 'c6-12', hi: 'दृष्टिपात', tr: 'dṛṣṭipāt', en: 'a glance', hint: 'नज़र डालना' },
  { ch: 'c6-12', hi: 'तुच्छ', tr: 'tucch', en: 'insignificant, petty', hint: 'नगण्य, छोटा' },
  { ch: 'c6-12', hi: 'चौकन्ना', tr: 'caukannā', en: 'alert, watchful', hint: 'सावधान' },
  { ch: 'c6-12', hi: 'प्रवृत्ति', tr: 'pravṛtti', en: 'instinct, tendency', hint: 'स्वभाव, रुझान' },
  { ch: 'c6-12', hi: 'निरापद', tr: 'nirāpad', en: 'safe', hint: 'सुरक्षित' },
  { ch: 'c6-12', hi: 'द्वीप', tr: 'dvīp', en: 'island', hint: 'टापू' },
  { ch: 'c6-12', hi: 'भूमध्य रेखा', tr: 'bhūmadhya rekhā', en: 'equator', hint: 'पृथ्वी के बीच की काल्पनिक रेखा' },
  { ch: 'c6-12', hi: 'खानदान', tr: 'khāndān', en: 'family lineage', hint: 'वंश, कुल' },
  { ch: 'c6-12', hi: 'रिवाज़', tr: 'rivāz', en: 'custom', hint: 'प्रथा, चलन' },
  { ch: 'c6-12', hi: 'ऊख', tr: 'ūkh', en: 'sugarcane', hint: 'गन्ना' },
  { ch: 'c6-12', hi: 'प्रलोभन', tr: 'pralobhan', en: 'temptation, lure', hint: 'लालच' },
  { ch: 'c6-12', hi: 'चिरायु', tr: 'cirāyu', en: 'long-lived', hint: 'दीर्घजीवी' },
  // ---- Class 6, 13: पेड़ की बात ----
  { ch: 'c6-13', hi: 'सुकोमल', tr: 'sukomal', en: 'very tender, soft', hint: 'बहुत कोमल' },
  { ch: 'c6-13', hi: 'अंश', tr: 'anś', en: 'part, portion', hint: 'भाग, हिस्सा' },
  { ch: 'c6-13', hi: 'भेदना', tr: 'bhednā', en: 'to pierce through', hint: 'छेदना, पार करना' },
  { ch: 'c6-13', hi: 'परीक्षण', tr: 'parīkṣaṇ', en: 'experiment, test', hint: 'जाँच, प्रयोग' },
  { ch: 'c6-13', hi: 'औंधा', tr: 'aundhā', en: 'upside down', hint: 'उल्टा' },
  { ch: 'c6-13', hi: 'तरल', tr: 'taral', en: 'liquid', hint: 'बहने वाला, द्रव' },
  { ch: 'c6-13', hi: 'सूक्ष्मदर्शी', tr: 'sūkṣmadarśī', en: 'microscope', hint: 'बहुत छोटी चीज़ें दिखाने वाला यंत्र' },
  { ch: 'c6-13', hi: 'संचार', tr: 'sañcār', en: 'circulation, flow', hint: 'प्रवाह' },
  { ch: 'c6-13', hi: 'आहार', tr: 'āhār', en: 'food', hint: 'भोजन' },
  { ch: 'c6-13', hi: 'श्वास', tr: 'śvās', en: 'breath', hint: 'साँस' },
  { ch: 'c6-13', hi: 'विषाक्त', tr: 'viṣākt', en: 'poisonous', hint: 'ज़हरीला' },
  { ch: 'c6-13', hi: 'विधाता', tr: 'vidhātā', en: 'the Creator', hint: 'ईश्वर, ब्रह्मा' },
  { ch: 'c6-13', hi: 'अग्रसर', tr: 'agrasar', en: 'moving forward', hint: 'आगे बढ़ना' },
  { ch: 'c6-13', hi: 'पल्लवित', tr: 'pallavit', en: 'sprouting leaves, flourishing', hint: 'हरा-भरा होना' },
  { ch: 'c6-13', hi: 'ममता', tr: 'mamtā', en: 'motherly love', hint: 'माँ का प्रेम' },
  { ch: 'c6-13', hi: 'प्रफुल्लित', tr: 'praphullit', en: 'delighted, blooming', hint: 'बहुत प्रसन्न' },
  { ch: 'c6-13', hi: 'होड़', tr: 'hoṛ', en: 'race, competition', hint: 'प्रतिस्पर्धा' },
  { ch: 'c6-13', hi: 'अभाव', tr: 'abhāv', en: 'lack, absence', hint: 'कमी' },
  // ---- Class 7, 1: माँ, कह एक कहानी ----
  { ch: 'c7-01', hi: 'चेटी', tr: 'ceṭī', en: 'maidservant', hint: 'दासी, सेविका' },
  { ch: 'c7-01', hi: 'हठी', tr: 'haṭhī', en: 'stubborn', hint: 'ज़िद्दी' },
  { ch: 'c7-01', hi: 'उपवन', tr: 'upvan', en: 'garden', hint: 'बाग़, बगीचा' },
  { ch: 'c7-01', hi: 'तात', tr: 'tāt', en: 'father', hint: 'पिता' },
  { ch: 'c7-01', hi: 'भ्रमण', tr: 'bhramaṇ', en: 'a stroll, wandering', hint: 'घूमना, टहलना' },
  { ch: 'c7-01', hi: 'सुरभि', tr: 'surabhi', en: 'fragrance', hint: 'सुगंध, खुशबू' },
  { ch: 'c7-01', hi: 'खग', tr: 'khag', en: 'bird', hint: 'पक्षी, पंछी' },
  { ch: 'c7-01', hi: 'शर', tr: 'śar', en: 'arrow', hint: 'बाण, तीर' },
  { ch: 'c7-01', hi: 'आखेटक', tr: 'ākheṭak', en: 'hunter', hint: 'शिकारी' },
  { ch: 'c7-01', hi: 'आहत', tr: 'āhat', en: 'wounded', hint: 'घायल' },
  { ch: 'c7-01', hi: 'रक्षक', tr: 'rakṣak', en: 'protector', hint: 'रक्षा करने वाला' },
  { ch: 'c7-01', hi: 'भक्षक', tr: 'bhakṣak', en: 'devourer, one who eats', hint: 'खाने वाला' },
  { ch: 'c7-01', hi: 'विवाद', tr: 'vivād', en: 'dispute', hint: 'झगड़ा, बहस' },
  { ch: 'c7-01', hi: 'सदय', tr: 'saday', en: 'kind-hearted', hint: 'दयालु' },
  { ch: 'c7-01', hi: 'निर्दय', tr: 'nirday', en: 'cruel, merciless', hint: 'क्रूर, निर्दयी' },
  { ch: 'c7-01', hi: 'उभय', tr: 'ubhay', en: 'both', hint: 'दोनों' },
  { ch: 'c7-01', hi: 'न्यायालय', tr: 'nyāyālay', en: 'court of law', hint: 'अदालत' },
  { ch: 'c7-01', hi: 'निरपराध', tr: 'niraparādh', en: 'innocent', hint: 'बेकसूर, निर्दोष' },
  // ---- Class 7, 2: तीन बुद्धिमान ----
  { ch: 'c7-02', hi: 'लोककथा', tr: 'lokkathā', en: 'folk tale', hint: 'लोगों में प्रचलित कहानी' },
  { ch: 'c7-02', hi: 'निर्धन', tr: 'nirdhan', en: 'poor', hint: 'गरीब' },
  { ch: 'c7-02', hi: 'संचित', tr: 'sañcit', en: 'accumulated, saved up', hint: 'जमा किया हुआ' },
  { ch: 'c7-02', hi: 'पैनी', tr: 'painī', en: 'sharp, keen', hint: 'तेज़' },
  { ch: 'c7-02', hi: 'उन्नीस', tr: 'unnīs', en: 'inferior (literally nineteen)', hint: 'कम, पीछे' },
  { ch: 'c7-02', hi: 'पश्चात्', tr: 'paścāt', en: 'after', hint: 'बाद में' },
  { ch: 'c7-02', hi: 'चरवाहा', tr: 'carvāhā', en: 'shepherd, herder', hint: 'पशु चराने वाला' },
  { ch: 'c7-02', hi: 'वीरान', tr: 'vīrān', en: 'desolate', hint: 'सुनसान, उजाड़' },
  { ch: 'c7-02', hi: 'लाँघना', tr: 'lā̃ghnā', en: 'to cross over', hint: 'पार करना' },
  { ch: 'c7-02', hi: 'छाला', tr: 'chālā', en: 'blister', hint: 'फफोला' },
  { ch: 'c7-02', hi: 'मझला', tr: 'majhlā', en: 'middle (brother)', hint: 'बीच का' },
  { ch: 'c7-02', hi: 'शंका', tr: 'śaṅkā', en: 'doubt, suspicion', hint: 'संदेह' },
  { ch: 'c7-02', hi: 'रेवड़', tr: 'revaṛ', en: 'flock, herd', hint: 'भेड़-बकरियों का झुंड' },
  { ch: 'c7-02', hi: 'आवभगत', tr: 'āvbhagat', en: 'hospitality', hint: 'स्वागत-सत्कार' },
  { ch: 'c7-02', hi: 'अनुमान', tr: 'anumān', en: 'guess, inference', hint: 'अंदाज़ा' },
  { ch: 'c7-02', hi: 'ज्यों की त्यों', tr: 'jyõ kī tyõ', en: 'exactly as it was', hint: 'जैसी थी वैसी' },
  { ch: 'c7-02', hi: 'तीक्ष्ण', tr: 'tīkṣṇ', en: 'sharp, acute', hint: 'तेज़, पैनी' },
  { ch: 'c7-02', hi: 'कोष', tr: 'koṣ', en: 'treasury, store', hint: 'भंडार' },
  // ---- Class 7, 3: फूल और काँटा ----
  { ch: 'c7-03', hi: 'मेह', tr: 'meh', en: 'rain', hint: 'वर्षा, बारिश' },
  { ch: 'c7-03', hi: 'छेदना', tr: 'chednā', en: 'to pierce', hint: 'छेद करना' },
  { ch: 'c7-03', hi: 'वर', tr: 'var', en: 'fine, excellent', hint: 'श्रेष्ठ, सुंदर' },
  { ch: 'c7-03', hi: 'बसन', tr: 'basan', en: 'clothing', hint: 'वस्त्र, कपड़ा' },
  { ch: 'c7-03', hi: 'कतरना', tr: 'katarnā', en: 'to clip, cut off', hint: 'काटना' },
  { ch: 'c7-03', hi: 'भौंर', tr: 'bhaũr', en: 'bumblebee', hint: 'भँवरा' },
  { ch: 'c7-03', hi: 'बेधना', tr: 'bedhnā', en: 'to pierce, wound', hint: 'छेदना, घायल करना' },
  { ch: 'c7-03', hi: 'श्याम', tr: 'śyām', en: 'dark, black', hint: 'काला, साँवला' },
  { ch: 'c7-03', hi: 'अनूठा', tr: 'anūṭhā', en: 'unique', hint: 'अनोखा' },
  { ch: 'c7-03', hi: 'निज', tr: 'nij', en: 'one’s own', hint: 'अपना' },
  { ch: 'c7-03', hi: 'कली', tr: 'kalī', en: 'bud', hint: 'अधखिला फूल' },
  { ch: 'c7-03', hi: 'खटकना', tr: 'khaṭaknā', en: 'to irk, be a thorn in the eye', hint: 'बुरा लगना, चुभना' },
  { ch: 'c7-03', hi: 'सोहना', tr: 'sohnā', en: 'to look beautiful', hint: 'सुशोभित होना' },
  { ch: 'c7-03', hi: 'शीश', tr: 'śīś', en: 'head', hint: 'सिर' },
  { ch: 'c7-03', hi: 'कुल', tr: 'kul', en: 'family, lineage', hint: 'वंश, खानदान' },
  { ch: 'c7-03', hi: 'बड़प्पन', tr: 'baṛappan', en: 'greatness, nobility', hint: 'बड़ाई, महानता' },
  { ch: 'c7-03', hi: 'कसर', tr: 'kasar', en: 'shortfall, deficiency', hint: 'कमी' },
  // ---- Class 7, 4: पानी रे पानी ----
  { ch: 'c7-04', hi: 'भूगोल', tr: 'bhūgol', en: 'geography', hint: 'पृथ्वी का अध्ययन' },
  { ch: 'c7-04', hi: 'जल-चक्र', tr: 'jal-cakra', en: 'water cycle', hint: 'पानी का चक्र' },
  { ch: 'c7-04', hi: 'भाप', tr: 'bhāp', en: 'steam, vapour', hint: 'वाष्प' },
  { ch: 'c7-04', hi: 'बेवक्त', tr: 'bevaqt', en: 'at an odd time', hint: 'कुसमय, असमय' },
  { ch: 'c7-04', hi: 'टंटा', tr: 'ṭaṇṭā', en: 'quarrel, fuss', hint: 'झगड़ा' },
  { ch: 'c7-04', hi: 'हक', tr: 'haq', en: 'right, entitlement', hint: 'अधिकार' },
  { ch: 'c7-04', hi: 'मजबूरी', tr: 'majbūrī', en: 'compulsion, helplessness', hint: 'लाचारी' },
  { ch: 'c7-04', hi: 'अकाल', tr: 'akāl', en: 'famine, drought', hint: 'सूखा' },
  { ch: 'c7-04', hi: 'बाढ़', tr: 'bāṛh', en: 'flood', hint: 'पानी का सैलाब' },
  { ch: 'c7-04', hi: 'पहलू', tr: 'pahlū', en: 'aspect, side', hint: 'पक्ष' },
  { ch: 'c7-04', hi: 'छुटकारा', tr: 'chuṭkārā', en: 'relief, escape', hint: 'मुक्ति' },
  { ch: 'c7-04', hi: 'गुल्लक', tr: 'gullak', en: 'piggy bank', hint: 'पैसे जमा करने का बरतन' },
  { ch: 'c7-04', hi: 'भंडार', tr: 'bhaṇḍār', en: 'store, reserve', hint: 'संग्रह, खजाना' },
  { ch: 'c7-04', hi: 'रिसना', tr: 'risnā', en: 'to seep', hint: 'धीरे-धीरे टपकना' },
  { ch: 'c7-04', hi: 'भूजल', tr: 'bhūjal', en: 'groundwater', hint: 'ज़मीन के नीचे का पानी' },
  { ch: 'c7-04', hi: 'खजाना', tr: 'khazānā', en: 'treasure', hint: 'कोष' },
  { ch: 'c7-04', hi: 'लालच', tr: 'lālac', en: 'greed', hint: 'लोभ' },
  { ch: 'c7-04', hi: 'संग्रहण', tr: 'saṅgrahaṇ', en: 'collecting, storing', hint: 'जमा करना' },
  // ---- Class 7, 5: नहीं होना बीमार ----
  { ch: 'c7-05', hi: 'अवसर', tr: 'avsar', en: 'occasion, opportunity', hint: 'मौका' },
  { ch: 'c7-05', hi: 'माहौल', tr: 'māhaul', en: 'atmosphere', hint: 'वातावरण' },
  { ch: 'c7-05', hi: 'अभिवादन', tr: 'abhivādan', en: 'greeting', hint: 'नमस्कार' },
  { ch: 'c7-05', hi: 'साबूदाना', tr: 'sābūdānā', en: 'sago, tapioca pearls', hint: 'खीर में डलने वाला हल्का दाना' },
  { ch: 'c7-05', hi: 'ठाठ', tr: 'ṭhāṭh', en: 'luxury, style', hint: 'शान, आराम' },
  { ch: 'c7-05', hi: 'काश', tr: 'kāś', en: 'if only', hint: 'ऐसा होता तो' },
  { ch: 'c7-05', hi: 'बहाना', tr: 'bahānā', en: 'excuse, pretext', hint: 'झूठा कारण' },
  { ch: 'c7-05', hi: 'रज़ाई', tr: 'razāī', en: 'quilt', hint: 'गद्देदार ओढ़ना' },
  { ch: 'c7-05', hi: 'झपकी', tr: 'jhapkī', en: 'nap, doze', hint: 'हल्की नींद' },
  { ch: 'c7-05', hi: 'कराहना', tr: 'karāhnā', en: 'to groan', hint: 'दर्द से आवाज़ निकालना' },
  { ch: 'c7-05', hi: 'नब्ज़', tr: 'nabz', en: 'pulse', hint: 'नाड़ी' },
  { ch: 'c7-05', hi: 'साबित', tr: 'sābit', en: 'proven', hint: 'सिद्ध' },
  { ch: 'c7-05', hi: 'पुड़िया', tr: 'puṛiyā', en: 'small paper packet of medicine', hint: 'कागज़ में बँधी दवा' },
  { ch: 'c7-05', hi: 'काढ़ा', tr: 'kāṛhā', en: 'herbal decoction', hint: 'जड़ी-बूटियों का गरम पेय' },
  { ch: 'c7-05', hi: 'चहल-पहल', tr: 'cahal-pahal', en: 'hustle and bustle', hint: 'रौनक, हलचल' },
  { ch: 'c7-05', hi: 'भुक्कड़', tr: 'bhukkaṛ', en: 'glutton', hint: 'पेटू, बहुत खाने वाला' },
  { ch: 'c7-05', hi: 'कुढ़न', tr: 'kuṛhan', en: 'irritation, sulking', hint: 'चिढ़, जलन' },
  { ch: 'c7-05', hi: 'विकार', tr: 'vikār', en: 'bad thought, flaw', hint: 'बुरा भाव, खोट' },
  // ---- Class 7, 6: गिरिधर कविराय की कुंडलिया (Braj) ----
  { ch: 'c7-06', hi: 'कुंडलिया', tr: 'kuṇḍaliyā', en: 'a six-line verse form', hint: 'छह पंक्तियों का छंद' },
  { ch: 'c7-06', hi: 'बिचारे', tr: 'bicāre', en: 'having thought', hint: 'विचार करके, सोचकर' },
  { ch: 'c7-06', hi: 'पाछे', tr: 'pāche', en: 'afterwards', hint: 'पीछे, बाद में' },
  { ch: 'c7-06', hi: 'पछिताय', tr: 'pachitāy', en: 'regrets', hint: 'पश्चाताप करता है' },
  { ch: 'c7-06', hi: 'बिगारे', tr: 'bigāre', en: 'spoils', hint: 'बिगाड़ता है' },
  { ch: 'c7-06', hi: 'चित्त', tr: 'citt', en: 'mind, heart', hint: 'मन' },
  { ch: 'c7-06', hi: 'चैन', tr: 'cain', en: 'peace, rest', hint: 'शांति, आराम' },
  { ch: 'c7-06', hi: 'सन्मान', tr: 'sanmān', en: 'respect', hint: 'सम्मान, आदर' },
  { ch: 'c7-06', hi: 'भावै', tr: 'bhāvai', en: 'pleases', hint: 'अच्छा लगता है' },
  { ch: 'c7-06', hi: 'कछु', tr: 'kachu', en: 'some, anything', hint: 'कुछ' },
  { ch: 'c7-06', hi: 'टरत', tr: 'ṭarat', en: 'goes away, is removed', hint: 'टलता है, दूर होता है' },
  { ch: 'c7-06', hi: 'जिय', tr: 'jiy', en: 'heart', hint: 'जी, हृदय' },
  { ch: 'c7-06', hi: 'माहिं', tr: 'māhĩ', en: 'in, within', hint: 'में, भीतर' },
  { ch: 'c7-06', hi: 'बिसारि', tr: 'bisāri', en: 'forgetting', hint: 'भुलाकर' },
  { ch: 'c7-06', hi: 'सुधि', tr: 'sudhi', en: 'awareness, care', hint: 'ख़बर, ध्यान' },
  { ch: 'c7-06', hi: 'दुर्जन', tr: 'durjan', en: 'wicked person', hint: 'बुरा आदमी' },
  { ch: 'c7-06', hi: 'खता', tr: 'khatā', en: 'fault, mistake', hint: 'गलती, दोष' },
  { ch: 'c7-06', hi: 'परतीती', tr: 'partītī', en: 'faith, conviction', hint: 'प्रतीति, विश्वास' },
  // ---- Class 7, 7: वर्षा-बहार ----
  { ch: 'c7-07', hi: 'बहार', tr: 'bahār', en: 'bloom, splendour', hint: 'शोभा, रौनक' },
  { ch: 'c7-07', hi: 'लुभाना', tr: 'lubhānā', en: 'to entice, charm', hint: 'मोहित करना' },
  { ch: 'c7-07', hi: 'नभ', tr: 'nabh', en: 'sky', hint: 'आकाश' },
  { ch: 'c7-07', hi: 'घनघोर', tr: 'ghanghor', en: 'dense, thunderous', hint: 'बहुत घना' },
  { ch: 'c7-07', hi: 'मालिन', tr: 'mālin', en: 'woman gardener', hint: 'बाग की देखभाल करने वाली' },
  { ch: 'c7-07', hi: 'ताल', tr: 'tāl', en: 'pond', hint: 'तालाब' },
  { ch: 'c7-07', hi: 'जलचर', tr: 'jalcar', en: 'water creature', hint: 'पानी में रहने वाला जीव' },
  { ch: 'c7-07', hi: 'लखना', tr: 'lakhnā', en: 'to see, behold', hint: 'देखना' },
  { ch: 'c7-07', hi: 'पपीहा', tr: 'papīhā', en: 'rain bird (hawk-cuckoo)', hint: 'वर्षा में बोलने वाला पक्षी' },
  { ch: 'c7-07', hi: 'ग्रीष्म', tr: 'grīṣm', en: 'summer', hint: 'गरमी की ऋतु' },
  { ch: 'c7-07', hi: 'ताप', tr: 'tāp', en: 'heat', hint: 'गरमी' },
  { ch: 'c7-07', hi: 'सौरभ', tr: 'saurabh', en: 'fragrance', hint: 'सुगंध' },
  { ch: 'c7-07', hi: 'आमोद', tr: 'āmod', en: 'joy, delight', hint: 'आनंद, प्रसन्नता' },
  { ch: 'c7-07', hi: 'कतार', tr: 'katār', en: 'row, line', hint: 'पंक्ति' },
  { ch: 'c7-07', hi: 'मनहर', tr: 'manhar', en: 'charming', hint: 'मन को हरने वाला, मनोहर' },
  { ch: 'c7-07', hi: 'भाँति', tr: 'bhā̃ti', en: 'manner, way', hint: 'तरह, प्रकार' },
  { ch: 'c7-07', hi: 'शोभा', tr: 'śobhā', en: 'beauty, grace', hint: 'सुंदरता' },
  // ---- Class 7, 8: बिरजू महाराज से साक्षात्कार ----
  { ch: 'c7-08', hi: 'संघर्ष', tr: 'saṅgharṣ', en: 'struggle', hint: 'कठिन प्रयास' },
  { ch: 'c7-08', hi: 'हवेली', tr: 'havelī', en: 'mansion', hint: 'बड़ा पुराना घर' },
  { ch: 'c7-08', hi: 'देहांत', tr: 'dehānt', en: 'death, passing away', hint: 'मृत्यु' },
  { ch: 'c7-08', hi: 'आर्थिक', tr: 'ārthik', en: 'financial', hint: 'धन से जुड़ा' },
  { ch: 'c7-08', hi: 'उतार-चढ़ाव', tr: 'utār-caṛhāv', en: 'ups and downs', hint: 'घटना-बढ़ना' },
  { ch: 'c7-08', hi: 'कर्ज़', tr: 'qarz', en: 'loan, debt', hint: 'उधार, ऋण' },
  { ch: 'c7-08', hi: 'ज़री', tr: 'zarī', en: 'gold-thread embroidery', hint: 'सोने-चाँदी के तार का काम' },
  { ch: 'c7-08', hi: 'गुज़ारा', tr: 'guzārā', en: 'livelihood, getting by', hint: 'जीवन-यापन' },
  { ch: 'c7-08', hi: 'तालीम', tr: 'tālīm', en: 'training, education', hint: 'शिक्षा, प्रशिक्षण' },
  { ch: 'c7-08', hi: 'शिष्य', tr: 'śiṣya', en: 'disciple, student', hint: 'चेला, विद्यार्थी' },
  { ch: 'c7-08', hi: 'भेंट', tr: 'bheṇṭ', en: 'gift, offering', hint: 'उपहार' },
  { ch: 'c7-08', hi: 'रस्म', tr: 'rasm', en: 'ritual, custom', hint: 'रीति, प्रथा' },
  { ch: 'c7-08', hi: 'सामर्थ्य', tr: 'sāmarthya', en: 'capacity, ability', hint: 'क्षमता, शक्ति' },
  { ch: 'c7-08', hi: 'घराना', tr: 'gharānā', en: 'school or lineage of an art', hint: 'कला की परंपरा वाला परिवार' },
  { ch: 'c7-08', hi: 'मग्न', tr: 'magn', en: 'absorbed, engrossed', hint: 'लीन, डूबा हुआ' },
  { ch: 'c7-08', hi: 'शैली', tr: 'śailī', en: 'style', hint: 'ढंग, तरीका' },
  { ch: 'c7-08', hi: 'लय', tr: 'lay', en: 'rhythm', hint: 'ताल' },
  { ch: 'c7-08', hi: 'तपस्या', tr: 'tapasyā', en: 'penance, austerity', hint: 'तप, कठिन साधना' },
  // ---- Class 7, 9: चिड़िया ----
  { ch: 'c7-09', hi: 'प्रीति', tr: 'prīti', en: 'love, affection', hint: 'प्रेम' },
  { ch: 'c7-09', hi: 'बंदी', tr: 'bandī', en: 'prisoner, captive', hint: 'कैदी' },
  { ch: 'c7-09', hi: 'मुक्ति', tr: 'mukti', en: 'freedom, liberation', hint: 'छुटकारा, आज़ादी' },
  { ch: 'c7-09', hi: 'ज्ञात', tr: 'gyāt', en: 'known', hint: 'मालूम' },
  { ch: 'c7-09', hi: 'खंजन', tr: 'khañjan', en: 'wagtail (a small bird)', hint: 'एक छोटा पक्षी' },
  { ch: 'c7-09', hi: 'कपोत', tr: 'kapot', en: 'pigeon, dove', hint: 'कबूतर' },
  { ch: 'c7-09', hi: 'चातक', tr: 'cātak', en: 'rain-loving cuckoo', hint: 'पपीहा' },
  { ch: 'c7-09', hi: 'कोकिल', tr: 'kokil', en: 'cuckoo', hint: 'कोयल' },
  { ch: 'c7-09', hi: 'काक', tr: 'kāk', en: 'crow', hint: 'कौआ' },
  { ch: 'c7-09', hi: 'शुक', tr: 'śuk', en: 'parrot', hint: 'तोता' },
  { ch: 'c7-09', hi: 'श्रम', tr: 'śram', en: 'labour, effort', hint: 'मेहनत' },
  { ch: 'c7-09', hi: 'लोभ', tr: 'lobh', en: 'greed', hint: 'लालच' },
  { ch: 'c7-09', hi: 'हड़पना', tr: 'haṛapnā', en: 'to grab, usurp', hint: 'छीन लेना' },
  { ch: 'c7-09', hi: 'गगन', tr: 'gagan', en: 'sky', hint: 'आकाश' },
  { ch: 'c7-09', hi: 'विचरण', tr: 'vicaraṇ', en: 'roaming about', hint: 'घूमना, भ्रमण' },
  { ch: 'c7-09', hi: 'स्वच्छंद', tr: 'svacchand', en: 'free, unrestrained', hint: 'स्वतंत्र, आज़ाद' },
  { ch: 'c7-09', hi: 'बेड़ी', tr: 'beṛī', en: 'shackle, fetter', hint: 'पैर की ज़ंजीर' },
  { ch: 'c7-09', hi: 'द्रोह', tr: 'droh', en: 'hostility, malice', hint: 'शत्रुता, विद्रोह' },
  // ---- Class 7, 10: मीरा के पद (Braj/Rajasthani) ----
  { ch: 'c7-10', hi: 'नैनन', tr: 'nainan', en: 'eyes', hint: 'आँखों (में)' },
  { ch: 'c7-10', hi: 'नंदलाल', tr: 'nandlāl', en: 'Krishna, son of Nand', hint: 'श्रीकृष्ण' },
  { ch: 'c7-10', hi: 'मूरति', tr: 'mūrati', en: 'form, image', hint: 'मूर्ति, रूप' },
  { ch: 'c7-10', hi: 'साँवरि', tr: 'sā̃vari', en: 'dark-complexioned', hint: 'साँवली' },
  { ch: 'c7-10', hi: 'सुधा', tr: 'sudhā', en: 'nectar', hint: 'अमृत' },
  { ch: 'c7-10', hi: 'उर', tr: 'ur', en: 'chest, heart', hint: 'हृदय, छाती' },
  { ch: 'c7-10', hi: 'वैजंती माल', tr: 'vaijantī māl', en: 'garland of vaijayanti seeds', hint: 'वैजयंती के बीजों की माला' },
  { ch: 'c7-10', hi: 'क्षुद्र', tr: 'kṣudra', en: 'tiny, small', hint: 'छोटी' },
  { ch: 'c7-10', hi: 'घंटिका', tr: 'ghaṇṭikā', en: 'small bell', hint: 'छोटी घंटी' },
  { ch: 'c7-10', hi: 'कटितट', tr: 'kaṭitaṭ', en: 'waist', hint: 'कमर' },
  { ch: 'c7-10', hi: 'नूपुर', tr: 'nūpur', en: 'anklet', hint: 'पायल, घुँघरू' },
  { ch: 'c7-10', hi: 'वछल', tr: 'vachal', en: 'loving, affectionate', hint: 'वत्सल, स्नेही' },
  { ch: 'c7-10', hi: 'बदरिया', tr: 'badariyā', en: 'cloud', hint: 'बदली, बादल' },
  { ch: 'c7-10', hi: 'सावन', tr: 'sāvan', en: 'Shravan, the monsoon month', hint: 'श्रावण मास' },
  { ch: 'c7-10', hi: 'भनक', tr: 'bhanak', en: 'faint sound, inkling', hint: 'हल्की आवाज़, आहट' },
  { ch: 'c7-10', hi: 'चहुँ दिश', tr: 'cahũ diś', en: 'all four directions', hint: 'चारों दिशाएँ' },
  { ch: 'c7-10', hi: 'दामिन', tr: 'dāmin', en: 'lightning', hint: 'बिजली' },
  { ch: 'c7-10', hi: 'गिरधर', tr: 'girdhar', en: 'Krishna, the mountain-holder', hint: 'श्रीकृष्ण' }
];
if (typeof module === 'object' && module.exports) module.exports = HINDI;
